// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shoppb.proto

package shoppb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 解锁条件 ============
type CondType int32

const (
	CondType_COND_TYPE_UNKNOWN CondType = 0
	CondType_MIN_LEVEL         CondType = 1 // 最低等级要求
	CondType_UNLOCK_CARD       CondType = 2 // 需要解锁卡
)

// Enum value maps for CondType.
var (
	CondType_name = map[int32]string{
		0: "COND_TYPE_UNKNOWN",
		1: "MIN_LEVEL",
		2: "UNLOCK_CARD",
	}
	CondType_value = map[string]int32{
		"COND_TYPE_UNKNOWN": 0,
		"MIN_LEVEL":         1,
		"UNLOCK_CARD":       2,
	}
)

func (x CondType) Enum() *CondType {
	p := new(CondType)
	*p = x
	return p
}

func (x CondType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CondType) Descriptor() protoreflect.EnumDescriptor {
	return file_shoppb_proto_enumTypes[0].Descriptor()
}

func (CondType) Type() protoreflect.EnumType {
	return &file_shoppb_proto_enumTypes[0]
}

func (x CondType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CondType.Descriptor instead.
func (CondType) EnumDescriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{0}
}

// ============ 商店概览 ============
type ShopProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`       // 商店ID
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`  // 商店名称
	ShopType      int32                  `protobuf:"varint,3,opt,name=shop_type,json=shopType,proto3" json:"shop_type,omitempty"` // 商店类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfile) Reset() {
	*x = ShopProfile{}
	mi := &file_shoppb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfile) ProtoMessage() {}

func (x *ShopProfile) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfile.ProtoReflect.Descriptor instead.
func (*ShopProfile) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{0}
}

func (x *ShopProfile) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopProfile) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopProfile) GetShopType() int32 {
	if x != nil {
		return x.ShopType
	}
	return 0
}

// ============ 商品信息 ============
type GoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 商品ID (用于购买)
	BoughtNum     int64                  `protobuf:"varint,2,opt,name=bought_num,json=boughtNum,proto3" json:"bought_num,omitempty"`    // 已购买数量
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                             // 价格 (金币)
	LimitCount    int64                  `protobuf:"varint,4,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"` // 限购数量 (0=不限购)
	Unlocked      bool                   `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`                       // 是否已解锁
	ItemId        int64                  `protobuf:"varint,6,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 物品ID (即种子ID)
	ItemCount     int64                  `protobuf:"varint,7,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`    // 每次购买获得数量
	Conds         []*Cond                `protobuf:"bytes,8,rep,name=conds,proto3" json:"conds,omitempty"`                              // 解锁条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_shoppb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetBoughtNum() int64 {
	if x != nil {
		return x.BoughtNum
	}
	return 0
}

func (x *GoodsInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfo) GetLimitCount() int64 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *GoodsInfo) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *GoodsInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GoodsInfo) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *GoodsInfo) GetConds() []*Cond {
	if x != nil {
		return x.Conds
	}
	return nil
}

type Cond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`   // CondType
	Param         int64                  `protobuf:"varint,2,opt,name=param,proto3" json:"param,omitempty"` // 参数值 (如等级要求的等级数)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cond) Reset() {
	*x = Cond{}
	mi := &file_shoppb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cond) ProtoMessage() {}

func (x *Cond) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cond.ProtoReflect.Descriptor instead.
func (*Cond) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{2}
}

func (x *Cond) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Cond) GetParam() int64 {
	if x != nil {
		return x.Param
	}
	return 0
}

// --- 获取商店列表 ---
type ShopProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfilesRequest) Reset() {
	*x = ShopProfilesRequest{}
	mi := &file_shoppb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesRequest) ProtoMessage() {}

func (x *ShopProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesRequest.ProtoReflect.Descriptor instead.
func (*ShopProfilesRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{3}
}

type ShopProfilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopProfiles  []*ShopProfile         `protobuf:"bytes,1,rep,name=shop_profiles,json=shopProfiles,proto3" json:"shop_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfilesReply) Reset() {
	*x = ShopProfilesReply{}
	mi := &file_shoppb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesReply) ProtoMessage() {}

func (x *ShopProfilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesReply.ProtoReflect.Descriptor instead.
func (*ShopProfilesReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{4}
}

func (x *ShopProfilesReply) GetShopProfiles() []*ShopProfile {
	if x != nil {
		return x.ShopProfiles
	}
	return nil
}

// --- 获取商店商品 ---
type ShopInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfoRequest) Reset() {
	*x = ShopInfoRequest{}
	mi := &file_shoppb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoRequest) ProtoMessage() {}

func (x *ShopInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoRequest.ProtoReflect.Descriptor instead.
func (*ShopInfoRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{5}
}

func (x *ShopInfoRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ShopInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsList     []*GoodsInfo           `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfoReply) Reset() {
	*x = ShopInfoReply{}
	mi := &file_shoppb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoReply) ProtoMessage() {}

func (x *ShopInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoReply.ProtoReflect.Descriptor instead.
func (*ShopInfoReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{6}
}

func (x *ShopInfoReply) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

// --- 购买商品 ---
type BuyGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID (GoodsInfo.id)
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                        // 购买数量
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                    // 单价
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyGoodsRequest) Reset() {
	*x = BuyGoodsRequest{}
	mi := &file_shoppb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsRequest) ProtoMessage() {}

func (x *BuyGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsRequest.ProtoReflect.Descriptor instead.
func (*BuyGoodsRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{7}
}

func (x *BuyGoodsRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuyGoodsRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyGoodsRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyGoodsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         *GoodsInfo             `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`                          // 更新后的商品信息
	GetItems      []*corepb.Item         `protobuf:"bytes,2,rep,name=get_items,json=getItems,proto3" json:"get_items,omitempty"`    // 获得的物品
	CostItems     []*corepb.Item         `protobuf:"bytes,3,rep,name=cost_items,json=costItems,proto3" json:"cost_items,omitempty"` // 消耗的物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyGoodsReply) Reset() {
	*x = BuyGoodsReply{}
	mi := &file_shoppb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyGoodsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsReply) ProtoMessage() {}

func (x *BuyGoodsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsReply.ProtoReflect.Descriptor instead.
func (*BuyGoodsReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{8}
}

func (x *BuyGoodsReply) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *BuyGoodsReply) GetGetItems() []*corepb.Item {
	if x != nil {
		return x.GetItems
	}
	return nil
}

func (x *BuyGoodsReply) GetCostItems() []*corepb.Item {
	if x != nil {
		return x.CostItems
	}
	return nil
}

// --- 商品解锁推送 ---
type GoodsUnlockNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsList     []*GoodsInfo           `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsUnlockNotify) Reset() {
	*x = GoodsUnlockNotify{}
	mi := &file_shoppb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsUnlockNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsUnlockNotify) ProtoMessage() {}

func (x *GoodsUnlockNotify) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsUnlockNotify.ProtoReflect.Descriptor instead.
func (*GoodsUnlockNotify) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsUnlockNotify) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

var File_shoppb_proto protoreflect.FileDescriptor

const file_shoppb_proto_rawDesc = "" +
	"\n" +
	"\fshoppb.proto\x12\rgamepb.shoppb\x1a\fcorepb.proto\"`\n" +
	"\vShopProfile\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12\x1b\n" +
	"\tshop_type\x18\x03 \x01(\x05R\bshopType\"\xf0\x01\n" +
	"\tGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"bought_num\x18\x02 \x01(\x03R\tboughtNum\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1f\n" +
	"\vlimit_count\x18\x04 \x01(\x03R\n" +
	"limitCount\x12\x1a\n" +
	"\bunlocked\x18\x05 \x01(\bR\bunlocked\x12\x17\n" +
	"\aitem_id\x18\x06 \x01(\x03R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_count\x18\a \x01(\x03R\titemCount\x12)\n" +
	"\x05conds\x18\b \x03(\v2\x13.gamepb.shoppb.CondR\x05conds\"0\n" +
	"\x04Cond\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x14\n" +
	"\x05param\x18\x02 \x01(\x03R\x05param\"\x15\n" +
	"\x13ShopProfilesRequest\"T\n" +
	"\x11ShopProfilesReply\x12?\n" +
	"\rshop_profiles\x18\x01 \x03(\v2\x1a.gamepb.shoppb.ShopProfileR\fshopProfiles\"*\n" +
	"\x0fShopInfoRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\"H\n" +
	"\rShopInfoReply\x127\n" +
	"\n" +
	"goods_list\x18\x01 \x03(\v2\x18.gamepb.shoppb.GoodsInfoR\tgoodsList\"T\n" +
	"\x0fBuyGoodsRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"\x97\x01\n" +
	"\rBuyGoodsReply\x12.\n" +
	"\x05goods\x18\x01 \x01(\v2\x18.gamepb.shoppb.GoodsInfoR\x05goods\x12)\n" +
	"\tget_items\x18\x02 \x03(\v2\f.corepb.ItemR\bgetItems\x12+\n" +
	"\n" +
	"cost_items\x18\x03 \x03(\v2\f.corepb.ItemR\tcostItems\"L\n" +
	"\x11GoodsUnlockNotify\x127\n" +
	"\n" +
	"goods_list\x18\x01 \x03(\v2\x18.gamepb.shoppb.GoodsInfoR\tgoodsList*A\n" +
	"\bCondType\x12\x15\n" +
	"\x11COND_TYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tMIN_LEVEL\x10\x01\x12\x0f\n" +
	"\vUNLOCK_CARD\x10\x02BFZDgithub.com/it00021hot/qq-farm-core/internal/farm/proto/shoppb;shoppbb\x06proto3"

var (
	file_shoppb_proto_rawDescOnce sync.Once
	file_shoppb_proto_rawDescData []byte
)

func file_shoppb_proto_rawDescGZIP() []byte {
	file_shoppb_proto_rawDescOnce.Do(func() {
		file_shoppb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppb_proto_rawDesc), len(file_shoppb_proto_rawDesc)))
	})
	return file_shoppb_proto_rawDescData
}

var file_shoppb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shoppb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shoppb_proto_goTypes = []any{
	(CondType)(0),               // 0: gamepb.shoppb.CondType
	(*ShopProfile)(nil),         // 1: gamepb.shoppb.ShopProfile
	(*GoodsInfo)(nil),           // 2: gamepb.shoppb.GoodsInfo
	(*Cond)(nil),                // 3: gamepb.shoppb.Cond
	(*ShopProfilesRequest)(nil), // 4: gamepb.shoppb.ShopProfilesRequest
	(*ShopProfilesReply)(nil),   // 5: gamepb.shoppb.ShopProfilesReply
	(*ShopInfoRequest)(nil),     // 6: gamepb.shoppb.ShopInfoRequest
	(*ShopInfoReply)(nil),       // 7: gamepb.shoppb.ShopInfoReply
	(*BuyGoodsRequest)(nil),     // 8: gamepb.shoppb.BuyGoodsRequest
	(*BuyGoodsReply)(nil),       // 9: gamepb.shoppb.BuyGoodsReply
	(*GoodsUnlockNotify)(nil),   // 10: gamepb.shoppb.GoodsUnlockNotify
	(*corepb.Item)(nil),         // 11: corepb.Item
}
var file_shoppb_proto_depIdxs = []int32{
	3,  // 0: gamepb.shoppb.GoodsInfo.conds:type_name -> gamepb.shoppb.Cond
	1,  // 1: gamepb.shoppb.ShopProfilesReply.shop_profiles:type_name -> gamepb.shoppb.ShopProfile
	2,  // 2: gamepb.shoppb.ShopInfoReply.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	2,  // 3: gamepb.shoppb.BuyGoodsReply.goods:type_name -> gamepb.shoppb.GoodsInfo
	11, // 4: gamepb.shoppb.BuyGoodsReply.get_items:type_name -> corepb.Item
	11, // 5: gamepb.shoppb.BuyGoodsReply.cost_items:type_name -> corepb.Item
	2,  // 6: gamepb.shoppb.GoodsUnlockNotify.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shoppb_proto_init() }
func file_shoppb_proto_init() {
	if File_shoppb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppb_proto_rawDesc), len(file_shoppb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoppb_proto_goTypes,
		DependencyIndexes: file_shoppb_proto_depIdxs,
		EnumInfos:         file_shoppb_proto_enumTypes,
		MessageInfos:      file_shoppb_proto_msgTypes,
	}.Build()
	File_shoppb_proto = out.File
	file_shoppb_proto_goTypes = nil
	file_shoppb_proto_depIdxs = nil
}
