// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: redpacketpb.proto

package redpacketpb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTodayClaimStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayClaimStatusRequest) Reset() {
	*x = GetTodayClaimStatusRequest{}
	mi := &file_redpacketpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayClaimStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayClaimStatusRequest) ProtoMessage() {}

func (x *GetTodayClaimStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayClaimStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTodayClaimStatusRequest) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{0}
}

type RedPacketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CanClaim      bool                   `protobuf:"varint,3,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedPacketInfo) Reset() {
	*x = RedPacketInfo{}
	mi := &file_redpacketpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedPacketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPacketInfo) ProtoMessage() {}

func (x *RedPacketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPacketInfo.ProtoReflect.Descriptor instead.
func (*RedPacketInfo) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{1}
}

func (x *RedPacketInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RedPacketInfo) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

type GetTodayClaimStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*RedPacketInfo       `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayClaimStatusReply) Reset() {
	*x = GetTodayClaimStatusReply{}
	mi := &file_redpacketpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayClaimStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayClaimStatusReply) ProtoMessage() {}

func (x *GetTodayClaimStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayClaimStatusReply.ProtoReflect.Descriptor instead.
func (*GetTodayClaimStatusReply) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodayClaimStatusReply) GetInfos() []*RedPacketInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ClaimRedPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRedPacketRequest) Reset() {
	*x = ClaimRedPacketRequest{}
	mi := &file_redpacketpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRedPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRedPacketRequest) ProtoMessage() {}

func (x *ClaimRedPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRedPacketRequest.ProtoReflect.Descriptor instead.
func (*ClaimRedPacketRequest) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRedPacketRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClaimRedPacketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Item          *corepb.Item           `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRedPacketReply) Reset() {
	*x = ClaimRedPacketReply{}
	mi := &file_redpacketpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRedPacketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRedPacketReply) ProtoMessage() {}

func (x *ClaimRedPacketReply) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRedPacketReply.ProtoReflect.Descriptor instead.
func (*ClaimRedPacketReply) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimRedPacketReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClaimRedPacketReply) GetItem() *corepb.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_redpacketpb_proto protoreflect.FileDescriptor

const file_redpacketpb_proto_rawDesc = "" +
	"\n" +
	"\x11redpacketpb.proto\x12\x12gamepb.redpacketpb\x1a\fcorepb.proto\"\x1c\n" +
	"\x1aGetTodayClaimStatusRequest\"<\n" +
	"\rRedPacketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tcan_claim\x18\x03 \x01(\bR\bcanClaim\"S\n" +
	"\x18GetTodayClaimStatusReply\x127\n" +
	"\x05infos\x18\x01 \x03(\v2!.gamepb.redpacketpb.RedPacketInfoR\x05infos\"'\n" +
	"\x15ClaimRedPacketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"O\n" +
	"\x13ClaimRedPacketReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12 \n" +
	"\x04item\x18\x02 \x01(\v2\f.corepb.ItemR\x04item2\xed\x01\n" +
	"\x10RedPacketService\x12s\n" +
	"\x13GetTodayClaimStatus\x12..gamepb.redpacketpb.GetTodayClaimStatusRequest\x1a,.gamepb.redpacketpb.GetTodayClaimStatusReply\x12d\n" +
	"\x0eClaimRedPacket\x12).gamepb.redpacketpb.ClaimRedPacketRequest\x1a'.gamepb.redpacketpb.ClaimRedPacketReplyBPZNgithub.com/it00021hot/qq-farm-core/internal/farm/proto/redpacketpb;redpacketpbb\x06proto3"

var (
	file_redpacketpb_proto_rawDescOnce sync.Once
	file_redpacketpb_proto_rawDescData []byte
)

func file_redpacketpb_proto_rawDescGZIP() []byte {
	file_redpacketpb_proto_rawDescOnce.Do(func() {
		file_redpacketpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redpacketpb_proto_rawDesc), len(file_redpacketpb_proto_rawDesc)))
	})
	return file_redpacketpb_proto_rawDescData
}

var file_redpacketpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_redpacketpb_proto_goTypes = []any{
	(*GetTodayClaimStatusRequest)(nil), // 0: gamepb.redpacketpb.GetTodayClaimStatusRequest
	(*RedPacketInfo)(nil),              // 1: gamepb.redpacketpb.RedPacketInfo
	(*GetTodayClaimStatusReply)(nil),   // 2: gamepb.redpacketpb.GetTodayClaimStatusReply
	(*ClaimRedPacketRequest)(nil),      // 3: gamepb.redpacketpb.ClaimRedPacketRequest
	(*ClaimRedPacketReply)(nil),        // 4: gamepb.redpacketpb.ClaimRedPacketReply
	(*corepb.Item)(nil),                // 5: corepb.Item
}
var file_redpacketpb_proto_depIdxs = []int32{
	1, // 0: gamepb.redpacketpb.GetTodayClaimStatusReply.infos:type_name -> gamepb.redpacketpb.RedPacketInfo
	5, // 1: gamepb.redpacketpb.ClaimRedPacketReply.item:type_name -> corepb.Item
	0, // 2: gamepb.redpacketpb.RedPacketService.GetTodayClaimStatus:input_type -> gamepb.redpacketpb.GetTodayClaimStatusRequest
	3, // 3: gamepb.redpacketpb.RedPacketService.ClaimRedPacket:input_type -> gamepb.redpacketpb.ClaimRedPacketRequest
	2, // 4: gamepb.redpacketpb.RedPacketService.GetTodayClaimStatus:output_type -> gamepb.redpacketpb.GetTodayClaimStatusReply
	4, // 5: gamepb.redpacketpb.RedPacketService.ClaimRedPacket:output_type -> gamepb.redpacketpb.ClaimRedPacketReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_redpacketpb_proto_init() }
func file_redpacketpb_proto_init() {
	if File_redpacketpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redpacketpb_proto_rawDesc), len(file_redpacketpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redpacketpb_proto_goTypes,
		DependencyIndexes: file_redpacketpb_proto_depIdxs,
		MessageInfos:      file_redpacketpb_proto_msgTypes,
	}.Build()
	File_redpacketpb_proto = out.File
	file_redpacketpb_proto_goTypes = nil
	file_redpacketpb_proto_depIdxs = nil
}
