// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: interactpb.proto

package interactpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ActionType    int32                  `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	VisitorGid    int64                  `protobuf:"varint,3,opt,name=visitor_gid,json=visitorGid,proto3" json:"visitor_gid,omitempty"`
	Nick          string                 `protobuf:"bytes,4,opt,name=nick,proto3" json:"nick,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CropId        int32                  `protobuf:"varint,6,opt,name=crop_id,json=cropId,proto3" json:"crop_id,omitempty"`
	CropCount     int32                  `protobuf:"varint,7,opt,name=crop_count,json=cropCount,proto3" json:"crop_count,omitempty"`
	Times         int32                  `protobuf:"varint,8,opt,name=times,proto3" json:"times,omitempty"`
	FromType      int32                  `protobuf:"varint,9,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	Level         int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Extra         *InteractRecord_Extra  `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecord) Reset() {
	*x = InteractRecord{}
	mi := &file_interactpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecord) ProtoMessage() {}

func (x *InteractRecord) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecord.ProtoReflect.Descriptor instead.
func (*InteractRecord) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{0}
}

func (x *InteractRecord) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *InteractRecord) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *InteractRecord) GetVisitorGid() int64 {
	if x != nil {
		return x.VisitorGid
	}
	return 0
}

func (x *InteractRecord) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *InteractRecord) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *InteractRecord) GetCropId() int32 {
	if x != nil {
		return x.CropId
	}
	return 0
}

func (x *InteractRecord) GetCropCount() int32 {
	if x != nil {
		return x.CropCount
	}
	return 0
}

func (x *InteractRecord) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *InteractRecord) GetFromType() int32 {
	if x != nil {
		return x.FromType
	}
	return 0
}

func (x *InteractRecord) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *InteractRecord) GetExtra() *InteractRecord_Extra {
	if x != nil {
		return x.Extra
	}
	return nil
}

type InteractRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecordsRequest) Reset() {
	*x = InteractRecordsRequest{}
	mi := &file_interactpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsRequest) ProtoMessage() {}

func (x *InteractRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsRequest.ProtoReflect.Descriptor instead.
func (*InteractRecordsRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{1}
}

type InteractRecordsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*InteractRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecordsReply) Reset() {
	*x = InteractRecordsReply{}
	mi := &file_interactpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsReply) ProtoMessage() {}

func (x *InteractRecordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsReply.ProtoReflect.Descriptor instead.
func (*InteractRecordsReply) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{2}
}

func (x *InteractRecordsReply) GetRecords() []*InteractRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// --- 获取互动信息 ---
type InteractInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorGid    int64                  `protobuf:"varint,1,opt,name=visitor_gid,json=visitorGid,proto3" json:"visitor_gid,omitempty"`
	Nick          string                 `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ActionType    int32                  `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ServerTime    int64                  `protobuf:"varint,5,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	CropId        int32                  `protobuf:"varint,6,opt,name=crop_id,json=cropId,proto3" json:"crop_id,omitempty"`
	CropCount     int32                  `protobuf:"varint,7,opt,name=crop_count,json=cropCount,proto3" json:"crop_count,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractInfo) Reset() {
	*x = InteractInfo{}
	mi := &file_interactpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractInfo) ProtoMessage() {}

func (x *InteractInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractInfo.ProtoReflect.Descriptor instead.
func (*InteractInfo) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{3}
}

func (x *InteractInfo) GetVisitorGid() int64 {
	if x != nil {
		return x.VisitorGid
	}
	return 0
}

func (x *InteractInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *InteractInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *InteractInfo) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *InteractInfo) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *InteractInfo) GetCropId() int32 {
	if x != nil {
		return x.CropId
	}
	return 0
}

func (x *InteractInfo) GetCropCount() int32 {
	if x != nil {
		return x.CropCount
	}
	return 0
}

func (x *InteractInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetInteractInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractInfoRequest) Reset() {
	*x = GetInteractInfoRequest{}
	mi := &file_interactpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractInfoRequest) ProtoMessage() {}

func (x *GetInteractInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInteractInfoRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{4}
}

type GetInteractInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*InteractInfo        `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractInfoReply) Reset() {
	*x = GetInteractInfoReply{}
	mi := &file_interactpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractInfoReply) ProtoMessage() {}

func (x *GetInteractInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractInfoReply.ProtoReflect.Descriptor instead.
func (*GetInteractInfoReply) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetInteractInfoReply) GetInfos() []*InteractInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// --- 获取互动摘要 ---
type InteractSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalWater       int64                  `protobuf:"varint,1,opt,name=total_water,json=totalWater,proto3" json:"total_water,omitempty"`
	TotalInsecticide int64                  `protobuf:"varint,2,opt,name=total_insecticide,json=totalInsecticide,proto3" json:"total_insecticide,omitempty"`
	TotalWeed        int64                  `protobuf:"varint,3,opt,name=total_weed,json=totalWeed,proto3" json:"total_weed,omitempty"`
	TotalSteal       int64                  `protobuf:"varint,4,opt,name=total_steal,json=totalSteal,proto3" json:"total_steal,omitempty"`
	TotalStolen      int64                  `protobuf:"varint,5,opt,name=total_stolen,json=totalStolen,proto3" json:"total_stolen,omitempty"`
	VisitorCount     int64                  `protobuf:"varint,6,opt,name=visitor_count,json=visitorCount,proto3" json:"visitor_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InteractSummary) Reset() {
	*x = InteractSummary{}
	mi := &file_interactpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractSummary) ProtoMessage() {}

func (x *InteractSummary) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractSummary.ProtoReflect.Descriptor instead.
func (*InteractSummary) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{6}
}

func (x *InteractSummary) GetTotalWater() int64 {
	if x != nil {
		return x.TotalWater
	}
	return 0
}

func (x *InteractSummary) GetTotalInsecticide() int64 {
	if x != nil {
		return x.TotalInsecticide
	}
	return 0
}

func (x *InteractSummary) GetTotalWeed() int64 {
	if x != nil {
		return x.TotalWeed
	}
	return 0
}

func (x *InteractSummary) GetTotalSteal() int64 {
	if x != nil {
		return x.TotalSteal
	}
	return 0
}

func (x *InteractSummary) GetTotalStolen() int64 {
	if x != nil {
		return x.TotalStolen
	}
	return 0
}

func (x *InteractSummary) GetVisitorCount() int64 {
	if x != nil {
		return x.VisitorCount
	}
	return 0
}

type GetInteractSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractSummaryRequest) Reset() {
	*x = GetInteractSummaryRequest{}
	mi := &file_interactpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractSummaryRequest) ProtoMessage() {}

func (x *GetInteractSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetInteractSummaryRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{7}
}

type GetInteractSummaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *InteractSummary       `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractSummaryReply) Reset() {
	*x = GetInteractSummaryReply{}
	mi := &file_interactpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractSummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractSummaryReply) ProtoMessage() {}

func (x *GetInteractSummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractSummaryReply.ProtoReflect.Descriptor instead.
func (*GetInteractSummaryReply) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{8}
}

func (x *GetInteractSummaryReply) GetSummary() *InteractSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// --- 关闭互动弹窗 ---
type DismissInteractPopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissInteractPopupRequest) Reset() {
	*x = DismissInteractPopupRequest{}
	mi := &file_interactpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissInteractPopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissInteractPopupRequest) ProtoMessage() {}

func (x *DismissInteractPopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissInteractPopupRequest.ProtoReflect.Descriptor instead.
func (*DismissInteractPopupRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{9}
}

type DismissInteractPopupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissInteractPopupReply) Reset() {
	*x = DismissInteractPopupReply{}
	mi := &file_interactpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissInteractPopupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissInteractPopupReply) ProtoMessage() {}

func (x *DismissInteractPopupReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissInteractPopupReply.ProtoReflect.Descriptor instead.
func (*DismissInteractPopupReply) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{10}
}

type InteractRecord_Extra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandId        int32                  `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`
	Flag1         int32                  `protobuf:"varint,2,opt,name=flag1,proto3" json:"flag1,omitempty"`
	Flag2         int32                  `protobuf:"varint,3,opt,name=flag2,proto3" json:"flag2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecord_Extra) Reset() {
	*x = InteractRecord_Extra{}
	mi := &file_interactpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecord_Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecord_Extra) ProtoMessage() {}

func (x *InteractRecord_Extra) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecord_Extra.ProtoReflect.Descriptor instead.
func (*InteractRecord_Extra) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InteractRecord_Extra) GetLandId() int32 {
	if x != nil {
		return x.LandId
	}
	return 0
}

func (x *InteractRecord_Extra) GetFlag1() int32 {
	if x != nil {
		return x.Flag1
	}
	return 0
}

func (x *InteractRecord_Extra) GetFlag2() int32 {
	if x != nil {
		return x.Flag2
	}
	return 0
}

var File_interactpb_proto protoreflect.FileDescriptor

const file_interactpb_proto_rawDesc = "" +
	"\n" +
	"\x10interactpb.proto\x12\x11gamepb.interactpb\"\xb4\x03\n" +
	"\x0eInteractRecord\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\x05R\n" +
	"actionType\x12\x1f\n" +
	"\vvisitor_gid\x18\x03 \x01(\x03R\n" +
	"visitorGid\x12\x12\n" +
	"\x04nick\x18\x04 \x01(\tR\x04nick\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x17\n" +
	"\acrop_id\x18\x06 \x01(\x05R\x06cropId\x12\x1d\n" +
	"\n" +
	"crop_count\x18\a \x01(\x05R\tcropCount\x12\x14\n" +
	"\x05times\x18\b \x01(\x05R\x05times\x12\x1b\n" +
	"\tfrom_type\x18\t \x01(\x05R\bfromType\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12=\n" +
	"\x05extra\x18\v \x01(\v2'.gamepb.interactpb.InteractRecord.ExtraR\x05extra\x1aL\n" +
	"\x05Extra\x12\x17\n" +
	"\aland_id\x18\x01 \x01(\x05R\x06landId\x12\x14\n" +
	"\x05flag1\x18\x02 \x01(\x05R\x05flag1\x12\x14\n" +
	"\x05flag2\x18\x03 \x01(\x05R\x05flag2\"\x18\n" +
	"\x16InteractRecordsRequest\"S\n" +
	"\x14InteractRecordsReply\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.gamepb.interactpb.InteractRecordR\arecords\"\xf2\x01\n" +
	"\fInteractInfo\x12\x1f\n" +
	"\vvisitor_gid\x18\x01 \x01(\x03R\n" +
	"visitorGid\x12\x12\n" +
	"\x04nick\x18\x02 \x01(\tR\x04nick\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\x05R\n" +
	"actionType\x12\x1f\n" +
	"\vserver_time\x18\x05 \x01(\x03R\n" +
	"serverTime\x12\x17\n" +
	"\acrop_id\x18\x06 \x01(\x05R\x06cropId\x12\x1d\n" +
	"\n" +
	"crop_count\x18\a \x01(\x05R\tcropCount\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\"\x18\n" +
	"\x16GetInteractInfoRequest\"M\n" +
	"\x14GetInteractInfoReply\x125\n" +
	"\x05infos\x18\x01 \x03(\v2\x1f.gamepb.interactpb.InteractInfoR\x05infos\"\xe7\x01\n" +
	"\x0fInteractSummary\x12\x1f\n" +
	"\vtotal_water\x18\x01 \x01(\x03R\n" +
	"totalWater\x12+\n" +
	"\x11total_insecticide\x18\x02 \x01(\x03R\x10totalInsecticide\x12\x1d\n" +
	"\n" +
	"total_weed\x18\x03 \x01(\x03R\ttotalWeed\x12\x1f\n" +
	"\vtotal_steal\x18\x04 \x01(\x03R\n" +
	"totalSteal\x12!\n" +
	"\ftotal_stolen\x18\x05 \x01(\x03R\vtotalStolen\x12#\n" +
	"\rvisitor_count\x18\x06 \x01(\x03R\fvisitorCount\"\x1b\n" +
	"\x19GetInteractSummaryRequest\"W\n" +
	"\x17GetInteractSummaryReply\x12<\n" +
	"\asummary\x18\x01 \x01(\v2\".gamepb.interactpb.InteractSummaryR\asummary\"\x1d\n" +
	"\x1bDismissInteractPopupRequest\"\x1b\n" +
	"\x19DismissInteractPopupReplyBKZIgithub.com/it00021hot/qq-farm-core/internal/farm/proto/interactpb;interactpbb\x06proto3"

var (
	file_interactpb_proto_rawDescOnce sync.Once
	file_interactpb_proto_rawDescData []byte
)

func file_interactpb_proto_rawDescGZIP() []byte {
	file_interactpb_proto_rawDescOnce.Do(func() {
		file_interactpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interactpb_proto_rawDesc), len(file_interactpb_proto_rawDesc)))
	})
	return file_interactpb_proto_rawDescData
}

var file_interactpb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_interactpb_proto_goTypes = []any{
	(*InteractRecord)(nil),              // 0: gamepb.interactpb.InteractRecord
	(*InteractRecordsRequest)(nil),      // 1: gamepb.interactpb.InteractRecordsRequest
	(*InteractRecordsReply)(nil),        // 2: gamepb.interactpb.InteractRecordsReply
	(*InteractInfo)(nil),                // 3: gamepb.interactpb.InteractInfo
	(*GetInteractInfoRequest)(nil),      // 4: gamepb.interactpb.GetInteractInfoRequest
	(*GetInteractInfoReply)(nil),        // 5: gamepb.interactpb.GetInteractInfoReply
	(*InteractSummary)(nil),             // 6: gamepb.interactpb.InteractSummary
	(*GetInteractSummaryRequest)(nil),   // 7: gamepb.interactpb.GetInteractSummaryRequest
	(*GetInteractSummaryReply)(nil),     // 8: gamepb.interactpb.GetInteractSummaryReply
	(*DismissInteractPopupRequest)(nil), // 9: gamepb.interactpb.DismissInteractPopupRequest
	(*DismissInteractPopupReply)(nil),   // 10: gamepb.interactpb.DismissInteractPopupReply
	(*InteractRecord_Extra)(nil),        // 11: gamepb.interactpb.InteractRecord.Extra
}
var file_interactpb_proto_depIdxs = []int32{
	11, // 0: gamepb.interactpb.InteractRecord.extra:type_name -> gamepb.interactpb.InteractRecord.Extra
	0,  // 1: gamepb.interactpb.InteractRecordsReply.records:type_name -> gamepb.interactpb.InteractRecord
	3,  // 2: gamepb.interactpb.GetInteractInfoReply.infos:type_name -> gamepb.interactpb.InteractInfo
	6,  // 3: gamepb.interactpb.GetInteractSummaryReply.summary:type_name -> gamepb.interactpb.InteractSummary
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_interactpb_proto_init() }
func file_interactpb_proto_init() {
	if File_interactpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interactpb_proto_rawDesc), len(file_interactpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interactpb_proto_goTypes,
		DependencyIndexes: file_interactpb_proto_depIdxs,
		MessageInfos:      file_interactpb_proto_msgTypes,
	}.Build()
	File_interactpb_proto = out.File
	file_interactpb_proto_goTypes = nil
	file_interactpb_proto_depIdxs = nil
}
