// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: userpb.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 登录请求 ============
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 字段 1,2 保留未使用
	SharerId      int64       `protobuf:"varint,3,opt,name=sharer_id,json=sharerId,proto3" json:"sharer_id,omitempty"`
	SharerOpenId  string      `protobuf:"bytes,4,opt,name=sharer_open_id,json=sharerOpenId,proto3" json:"sharer_open_id,omitempty"`
	DeviceInfo    *DeviceInfo `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	ShareCfgId    int64       `protobuf:"varint,6,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	SceneId       string      `protobuf:"bytes,7,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	ReportData    *ReportData `protobuf:"bytes,8,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_userpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetSharerId() int64 {
	if x != nil {
		return x.SharerId
	}
	return 0
}

func (x *LoginRequest) GetSharerOpenId() string {
	if x != nil {
		return x.SharerOpenId
	}
	return ""
}

func (x *LoginRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *LoginRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

func (x *LoginRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *LoginRequest) GetReportData() *ReportData {
	if x != nil {
		return x.ReportData
	}
	return nil
}

// 设备信息
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // e.g. "1.6.0.8_20251224"
	SysSoftware   string                 `protobuf:"bytes,2,opt,name=sys_software,json=sysSoftware,proto3" json:"sys_software,omitempty"`       // e.g. "Windows Unknown x64"
	SysHardware   string                 `protobuf:"bytes,3,opt,name=sys_hardware,json=sysHardware,proto3" json:"sys_hardware,omitempty"`
	TelecomOper   string                 `protobuf:"bytes,4,opt,name=telecom_oper,json=telecomOper,proto3" json:"telecom_oper,omitempty"`
	Network       string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"` // e.g. "wifi"
	ScreenWidth   int64                  `protobuf:"varint,6,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int64                  `protobuf:"varint,7,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	Density       float32                `protobuf:"fixed32,8,opt,name=density,proto3" json:"density,omitempty"`
	Cpu           string                 `protobuf:"bytes,9,opt,name=cpu,proto3" json:"cpu,omitempty"` // e.g. "microsoft"
	Memory        int64                  `protobuf:"varint,10,opt,name=memory,proto3" json:"memory,omitempty"`
	GlRender      string                 `protobuf:"bytes,11,opt,name=gl_render,json=glRender,proto3" json:"gl_render,omitempty"`
	GlVersion     string                 `protobuf:"bytes,12,opt,name=gl_version,json=glVersion,proto3" json:"gl_version,omitempty"`
	DeviceId      string                 `protobuf:"bytes,13,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AndroidOaid   string                 `protobuf:"bytes,14,opt,name=android_oaid,json=androidOaid,proto3" json:"android_oaid,omitempty"`
	IosCaid       string                 `protobuf:"bytes,15,opt,name=ios_caid,json=iosCaid,proto3" json:"ios_caid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_userpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *DeviceInfo) GetSysSoftware() string {
	if x != nil {
		return x.SysSoftware
	}
	return ""
}

func (x *DeviceInfo) GetSysHardware() string {
	if x != nil {
		return x.SysHardware
	}
	return ""
}

func (x *DeviceInfo) GetTelecomOper() string {
	if x != nil {
		return x.TelecomOper
	}
	return ""
}

func (x *DeviceInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DeviceInfo) GetScreenWidth() int64 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *DeviceInfo) GetScreenHeight() int64 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *DeviceInfo) GetDensity() float32 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *DeviceInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *DeviceInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *DeviceInfo) GetGlRender() string {
	if x != nil {
		return x.GlRender
	}
	return ""
}

func (x *DeviceInfo) GetGlVersion() string {
	if x != nil {
		return x.GlVersion
	}
	return ""
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetAndroidOaid() string {
	if x != nil {
		return x.AndroidOaid
	}
	return ""
}

func (x *DeviceInfo) GetIosCaid() string {
	if x != nil {
		return x.IosCaid
	}
	return ""
}

// 上报数据
type ReportData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Callback        string                 `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	CdExtendInfo    string                 `protobuf:"bytes,2,opt,name=cd_extend_info,json=cdExtendInfo,proto3" json:"cd_extend_info,omitempty"`
	ClickId         string                 `protobuf:"bytes,3,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	ClueToken       string                 `protobuf:"bytes,4,opt,name=clue_token,json=clueToken,proto3" json:"clue_token,omitempty"`
	MinigameChannel string                 `protobuf:"bytes,5,opt,name=minigame_channel,json=minigameChannel,proto3" json:"minigame_channel,omitempty"`
	MinigamePlatid  int32                  `protobuf:"varint,6,opt,name=minigame_platid,json=minigamePlatid,proto3" json:"minigame_platid,omitempty"`
	ReqId           string                 `protobuf:"bytes,7,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Trackid         string                 `protobuf:"bytes,8,opt,name=trackid,proto3" json:"trackid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportData) Reset() {
	*x = ReportData{}
	mi := &file_userpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportData) ProtoMessage() {}

func (x *ReportData) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportData.ProtoReflect.Descriptor instead.
func (*ReportData) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{2}
}

func (x *ReportData) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *ReportData) GetCdExtendInfo() string {
	if x != nil {
		return x.CdExtendInfo
	}
	return ""
}

func (x *ReportData) GetClickId() string {
	if x != nil {
		return x.ClickId
	}
	return ""
}

func (x *ReportData) GetClueToken() string {
	if x != nil {
		return x.ClueToken
	}
	return ""
}

func (x *ReportData) GetMinigameChannel() string {
	if x != nil {
		return x.MinigameChannel
	}
	return ""
}

func (x *ReportData) GetMinigamePlatid() int32 {
	if x != nil {
		return x.MinigamePlatid
	}
	return 0
}

func (x *ReportData) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *ReportData) GetTrackid() string {
	if x != nil {
		return x.Trackid
	}
	return ""
}

// ============ 登录回复 ============
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Basic *BasicInfo             `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	// ItemBag item_bag = 2;         // corepb.ItemBag, 复杂结构先跳过
	TimeNowMillis int64 `protobuf:"varint,3,opt,name=time_now_millis,json=timeNowMillis,proto3" json:"time_now_millis,omitempty"`
	IsFirstLogin  bool  `protobuf:"varint,4,opt,name=is_first_login,json=isFirstLogin,proto3" json:"is_first_login,omitempty"`
	// GuideInfo guide_info = 5;
	QqGroupInfos []*QQGroupInfo `protobuf:"bytes,6,rep,name=qq_group_infos,json=qqGroupInfos,proto3" json:"qq_group_infos,omitempty"`
	// Illustrated illustrated = 7;
	// repeated SystemUnlockItem unlocked_items = 8;
	VersionInfo *VersionInfo `protobuf:"bytes,9,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// MallMsg mall_msg = 10;
	QqFriendRecommendAuthorized int64 `protobuf:"varint,11,opt,name=qq_friend_recommend_authorized,json=qqFriendRecommendAuthorized,proto3" json:"qq_friend_recommend_authorized,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_userpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *LoginReply) GetTimeNowMillis() int64 {
	if x != nil {
		return x.TimeNowMillis
	}
	return 0
}

func (x *LoginReply) GetIsFirstLogin() bool {
	if x != nil {
		return x.IsFirstLogin
	}
	return false
}

func (x *LoginReply) GetQqGroupInfos() []*QQGroupInfo {
	if x != nil {
		return x.QqGroupInfos
	}
	return nil
}

func (x *LoginReply) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *LoginReply) GetQqFriendRecommendAuthorized() int64 {
	if x != nil {
		return x.QqFriendRecommendAuthorized
	}
	return 0
}

// 用户基本信息
type BasicInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Gid       int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level     int64                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp       int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold      int64                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	OpenId    string                 `protobuf:"bytes,6,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	AvatarUrl string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Remark    string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Signature string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender    int32                  `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	// repeated AvatarFrame equip_avatar_frames = 11;
	// map<int64, ShareInfo> share_infos = 12;
	AuthorizedStatus int32 `protobuf:"varint,13,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	DisableNudge     bool  `protobuf:"varint,14,opt,name=disable_nudge,json=disableNudge,proto3" json:"disable_nudge,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_userpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{4}
}

func (x *BasicInfo) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *BasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BasicInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *BasicInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *BasicInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *BasicInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *BasicInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BasicInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BasicInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *BasicInfo) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

func (x *BasicInfo) GetDisableNudge() bool {
	if x != nil {
		return x.DisableNudge
	}
	return false
}

// QQ群信息
type QQGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QqGroupId     string                 `protobuf:"bytes,1,opt,name=qq_group_id,json=qqGroupId,proto3" json:"qq_group_id,omitempty"`
	QqGroupName   string                 `protobuf:"bytes,2,opt,name=qq_group_name,json=qqGroupName,proto3" json:"qq_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QQGroupInfo) Reset() {
	*x = QQGroupInfo{}
	mi := &file_userpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QQGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQGroupInfo) ProtoMessage() {}

func (x *QQGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQGroupInfo.ProtoReflect.Descriptor instead.
func (*QQGroupInfo) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{5}
}

func (x *QQGroupInfo) GetQqGroupId() string {
	if x != nil {
		return x.QqGroupId
	}
	return ""
}

func (x *QQGroupInfo) GetQqGroupName() string {
	if x != nil {
		return x.QqGroupName
	}
	return ""
}

// 版本信息
type VersionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	VersionRecommend string                 `protobuf:"bytes,2,opt,name=version_recommend,json=versionRecommend,proto3" json:"version_recommend,omitempty"`
	VersionForce     string                 `protobuf:"bytes,3,opt,name=version_force,json=versionForce,proto3" json:"version_force,omitempty"`
	ResVersion       string                 `protobuf:"bytes,4,opt,name=res_version,json=resVersion,proto3" json:"res_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_userpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{6}
}

func (x *VersionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VersionInfo) GetVersionRecommend() string {
	if x != nil {
		return x.VersionRecommend
	}
	return ""
}

func (x *VersionInfo) GetVersionForce() string {
	if x != nil {
		return x.VersionForce
	}
	return ""
}

func (x *VersionInfo) GetResVersion() string {
	if x != nil {
		return x.ResVersion
	}
	return ""
}

// ============ 心跳 ============
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_userpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *HeartbeatRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	VersionInfo   *VersionInfo           `protobuf:"bytes,2,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_userpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatReply) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatReply) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

// ============ 上报分享点击 ============
// 用于已登录状态下处理分享链接（触发好友申请）
type ReportArkClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharerId      int64                  `protobuf:"varint,1,opt,name=sharer_id,json=sharerId,proto3" json:"sharer_id,omitempty"`
	SharerOpenId  string                 `protobuf:"bytes,2,opt,name=sharer_open_id,json=sharerOpenId,proto3" json:"sharer_open_id,omitempty"`
	ShareCfgId    int64                  `protobuf:"varint,3,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	SceneId       string                 `protobuf:"bytes,4,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArkClickRequest) Reset() {
	*x = ReportArkClickRequest{}
	mi := &file_userpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArkClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArkClickRequest) ProtoMessage() {}

func (x *ReportArkClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArkClickRequest.ProtoReflect.Descriptor instead.
func (*ReportArkClickRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{9}
}

func (x *ReportArkClickRequest) GetSharerId() int64 {
	if x != nil {
		return x.SharerId
	}
	return 0
}

func (x *ReportArkClickRequest) GetSharerOpenId() string {
	if x != nil {
		return x.SharerOpenId
	}
	return ""
}

func (x *ReportArkClickRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

func (x *ReportArkClickRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

type ReportArkClickReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArkClickReply) Reset() {
	*x = ReportArkClickReply{}
	mi := &file_userpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArkClickReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArkClickReply) ProtoMessage() {}

func (x *ReportArkClickReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArkClickReply.ProtoReflect.Descriptor instead.
func (*ReportArkClickReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{10}
}

// ============ 批量上报客户端流程 ============
type BatchClientReportFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ClientFlowItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClientReportFlowRequest) Reset() {
	*x = BatchClientReportFlowRequest{}
	mi := &file_userpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClientReportFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClientReportFlowRequest) ProtoMessage() {}

func (x *BatchClientReportFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClientReportFlowRequest.ProtoReflect.Descriptor instead.
func (*BatchClientReportFlowRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{11}
}

func (x *BatchClientReportFlowRequest) GetItems() []*ClientFlowItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClientFlowItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params        string                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFlowItem) Reset() {
	*x = ClientFlowItem{}
	mi := &file_userpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFlowItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFlowItem) ProtoMessage() {}

func (x *ClientFlowItem) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFlowItem.ProtoReflect.Descriptor instead.
func (*ClientFlowItem) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{12}
}

func (x *ClientFlowItem) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ClientFlowItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientFlowItem) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type BatchClientReportFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClientReportFlowReply) Reset() {
	*x = BatchClientReportFlowReply{}
	mi := &file_userpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClientReportFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClientReportFlowReply) ProtoMessage() {}

func (x *BatchClientReportFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClientReportFlowReply.ProtoReflect.Descriptor instead.
func (*BatchClientReportFlowReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{13}
}

// ============ 设置展示信息 ============
type SetDisplayInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayInfoRequest) Reset() {
	*x = SetDisplayInfoRequest{}
	mi := &file_userpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayInfoRequest) ProtoMessage() {}

func (x *SetDisplayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayInfoRequest.ProtoReflect.Descriptor instead.
func (*SetDisplayInfoRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{14}
}

func (x *SetDisplayInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDisplayInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetDisplayInfoRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *SetDisplayInfoRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type SetDisplayInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *BasicInfo             `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayInfoReply) Reset() {
	*x = SetDisplayInfoReply{}
	mi := &file_userpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayInfoReply) ProtoMessage() {}

func (x *SetDisplayInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayInfoReply.ProtoReflect.Descriptor instead.
func (*SetDisplayInfoReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{15}
}

func (x *SetDisplayInfoReply) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

// ============ 设置QQ好友推荐授权 ============
type SetQQFriendRecommendAuthorizedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    int64                  `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQQFriendRecommendAuthorizedRequest) Reset() {
	*x = SetQQFriendRecommendAuthorizedRequest{}
	mi := &file_userpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQQFriendRecommendAuthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQQFriendRecommendAuthorizedRequest) ProtoMessage() {}

func (x *SetQQFriendRecommendAuthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQQFriendRecommendAuthorizedRequest.ProtoReflect.Descriptor instead.
func (*SetQQFriendRecommendAuthorizedRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{16}
}

func (x *SetQQFriendRecommendAuthorizedRequest) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type SetQQFriendRecommendAuthorizedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    int64                  `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQQFriendRecommendAuthorizedReply) Reset() {
	*x = SetQQFriendRecommendAuthorizedReply{}
	mi := &file_userpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQQFriendRecommendAuthorizedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQQFriendRecommendAuthorizedReply) ProtoMessage() {}

func (x *SetQQFriendRecommendAuthorizedReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQQFriendRecommendAuthorizedReply.ProtoReflect.Descriptor instead.
func (*SetQQFriendRecommendAuthorizedReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{17}
}

func (x *SetQQFriendRecommendAuthorizedReply) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

// ============ 获取用户设置 ============
type GetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsRequest) Reset() {
	*x = GetUserSettingsRequest{}
	mi := &file_userpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsRequest) ProtoMessage() {}

func (x *GetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{18}
}

type UserSettings struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	QqFriendRecommendAuthorized int64                  `protobuf:"varint,1,opt,name=qq_friend_recommend_authorized,json=qqFriendRecommendAuthorized,proto3" json:"qq_friend_recommend_authorized,omitempty"`
	DisableNudge                bool                   `protobuf:"varint,2,opt,name=disable_nudge,json=disableNudge,proto3" json:"disable_nudge,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_userpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{19}
}

func (x *UserSettings) GetQqFriendRecommendAuthorized() int64 {
	if x != nil {
		return x.QqFriendRecommendAuthorized
	}
	return 0
}

func (x *UserSettings) GetDisableNudge() bool {
	if x != nil {
		return x.DisableNudge
	}
	return false
}

type GetUserSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsReply) Reset() {
	*x = GetUserSettingsReply{}
	mi := &file_userpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsReply) ProtoMessage() {}

func (x *GetUserSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsReply.ProtoReflect.Descriptor instead.
func (*GetUserSettingsReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserSettingsReply) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// ============ 批量获取用户信息 ============
type BatchGetBasicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gids          []int64                `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBasicInfoRequest) Reset() {
	*x = BatchGetBasicInfoRequest{}
	mi := &file_userpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBasicInfoRequest) ProtoMessage() {}

func (x *BatchGetBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchGetBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{21}
}

func (x *BatchGetBasicInfoRequest) GetGids() []int64 {
	if x != nil {
		return x.Gids
	}
	return nil
}

type BatchGetBasicInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*BasicInfo           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBasicInfoReply) Reset() {
	*x = BatchGetBasicInfoReply{}
	mi := &file_userpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBasicInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBasicInfoReply) ProtoMessage() {}

func (x *BatchGetBasicInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBasicInfoReply.ProtoReflect.Descriptor instead.
func (*BatchGetBasicInfoReply) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{22}
}

func (x *BatchGetBasicInfoReply) GetUsers() []*BasicInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 基本信息变化通知 (升级/金币变化等)
type BasicNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *BasicInfo             `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicNotify) Reset() {
	*x = BasicNotify{}
	mi := &file_userpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicNotify) ProtoMessage() {}

func (x *BasicNotify) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicNotify.ProtoReflect.Descriptor instead.
func (*BasicNotify) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{23}
}

func (x *BasicNotify) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

var File_userpb_proto protoreflect.FileDescriptor

const file_userpb_proto_rawDesc = "" +
	"\n" +
	"\fuserpb.proto\x12\rgamepb.userpb\"\x86\x02\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tsharer_id\x18\x03 \x01(\x03R\bsharerId\x12$\n" +
	"\x0esharer_open_id\x18\x04 \x01(\tR\fsharerOpenId\x12:\n" +
	"\vdevice_info\x18\x05 \x01(\v2\x19.gamepb.userpb.DeviceInfoR\n" +
	"deviceInfo\x12 \n" +
	"\fshare_cfg_id\x18\x06 \x01(\x03R\n" +
	"shareCfgId\x12\x19\n" +
	"\bscene_id\x18\a \x01(\tR\asceneId\x12:\n" +
	"\vreport_data\x18\b \x01(\v2\x19.gamepb.userpb.ReportDataR\n" +
	"reportData\"\xd9\x03\n" +
	"\n" +
	"DeviceInfo\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12!\n" +
	"\fsys_software\x18\x02 \x01(\tR\vsysSoftware\x12!\n" +
	"\fsys_hardware\x18\x03 \x01(\tR\vsysHardware\x12!\n" +
	"\ftelecom_oper\x18\x04 \x01(\tR\vtelecomOper\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12!\n" +
	"\fscreen_width\x18\x06 \x01(\x03R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\a \x01(\x03R\fscreenHeight\x12\x18\n" +
	"\adensity\x18\b \x01(\x02R\adensity\x12\x10\n" +
	"\x03cpu\x18\t \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\n" +
	" \x01(\x03R\x06memory\x12\x1b\n" +
	"\tgl_render\x18\v \x01(\tR\bglRender\x12\x1d\n" +
	"\n" +
	"gl_version\x18\f \x01(\tR\tglVersion\x12\x1b\n" +
	"\tdevice_id\x18\r \x01(\tR\bdeviceId\x12!\n" +
	"\fandroid_oaid\x18\x0e \x01(\tR\vandroidOaid\x12\x19\n" +
	"\bios_caid\x18\x0f \x01(\tR\aiosCaid\"\x8d\x02\n" +
	"\n" +
	"ReportData\x12\x1a\n" +
	"\bcallback\x18\x01 \x01(\tR\bcallback\x12$\n" +
	"\x0ecd_extend_info\x18\x02 \x01(\tR\fcdExtendInfo\x12\x19\n" +
	"\bclick_id\x18\x03 \x01(\tR\aclickId\x12\x1d\n" +
	"\n" +
	"clue_token\x18\x04 \x01(\tR\tclueToken\x12)\n" +
	"\x10minigame_channel\x18\x05 \x01(\tR\x0fminigameChannel\x12'\n" +
	"\x0fminigame_platid\x18\x06 \x01(\x05R\x0eminigamePlatid\x12\x15\n" +
	"\x06req_id\x18\a \x01(\tR\x05reqId\x12\x18\n" +
	"\atrackid\x18\b \x01(\tR\atrackid\"\xd0\x02\n" +
	"\n" +
	"LoginReply\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x18.gamepb.userpb.BasicInfoR\x05basic\x12&\n" +
	"\x0ftime_now_millis\x18\x03 \x01(\x03R\rtimeNowMillis\x12$\n" +
	"\x0eis_first_login\x18\x04 \x01(\bR\fisFirstLogin\x12@\n" +
	"\x0eqq_group_infos\x18\x06 \x03(\v2\x1a.gamepb.userpb.QQGroupInfoR\fqqGroupInfos\x12=\n" +
	"\fversion_info\x18\t \x01(\v2\x1a.gamepb.userpb.VersionInfoR\vversionInfo\x12C\n" +
	"\x1eqq_friend_recommend_authorized\x18\v \x01(\x03R\x1bqqFriendRecommendAuthorized\"\xc5\x02\n" +
	"\tBasicInfo\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x03R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x03R\x04gold\x12\x17\n" +
	"\aopen_id\x18\x06 \x01(\tR\x06openId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\x05R\x06gender\x12+\n" +
	"\x11authorized_status\x18\r \x01(\x05R\x10authorizedStatus\x12#\n" +
	"\rdisable_nudge\x18\x0e \x01(\bR\fdisableNudge\"Q\n" +
	"\vQQGroupInfo\x12\x1e\n" +
	"\vqq_group_id\x18\x01 \x01(\tR\tqqGroupId\x12\"\n" +
	"\rqq_group_name\x18\x02 \x01(\tR\vqqGroupName\"\x98\x01\n" +
	"\vVersionInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12+\n" +
	"\x11version_recommend\x18\x02 \x01(\tR\x10versionRecommend\x12#\n" +
	"\rversion_force\x18\x03 \x01(\tR\fversionForce\x12\x1f\n" +
	"\vres_version\x18\x04 \x01(\tR\n" +
	"resVersion\"K\n" +
	"\x10HeartbeatRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"p\n" +
	"\x0eHeartbeatReply\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12=\n" +
	"\fversion_info\x18\x02 \x01(\v2\x1a.gamepb.userpb.VersionInfoR\vversionInfo\"\x97\x01\n" +
	"\x15ReportArkClickRequest\x12\x1b\n" +
	"\tsharer_id\x18\x01 \x01(\x03R\bsharerId\x12$\n" +
	"\x0esharer_open_id\x18\x02 \x01(\tR\fsharerOpenId\x12 \n" +
	"\fshare_cfg_id\x18\x03 \x01(\x03R\n" +
	"shareCfgId\x12\x19\n" +
	"\bscene_id\x18\x04 \x01(\tR\asceneId\"\x15\n" +
	"\x13ReportArkClickReply\"S\n" +
	"\x1cBatchClientReportFlowRequest\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.gamepb.userpb.ClientFlowItemR\x05items\"e\n" +
	"\x0eClientFlowItem\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06params\x18\x03 \x01(\tR\x06params\"\x1c\n" +
	"\x1aBatchClientReportFlowReply\"\x80\x01\n" +
	"\x15SetDisplayInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"E\n" +
	"\x13SetDisplayInfoReply\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x18.gamepb.userpb.BasicInfoR\x05basic\"G\n" +
	"%SetQQFriendRecommendAuthorizedRequest\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\x03R\n" +
	"authorized\"E\n" +
	"#SetQQFriendRecommendAuthorizedReply\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\x03R\n" +
	"authorized\"\x18\n" +
	"\x16GetUserSettingsRequest\"x\n" +
	"\fUserSettings\x12C\n" +
	"\x1eqq_friend_recommend_authorized\x18\x01 \x01(\x03R\x1bqqFriendRecommendAuthorized\x12#\n" +
	"\rdisable_nudge\x18\x02 \x01(\bR\fdisableNudge\"O\n" +
	"\x14GetUserSettingsReply\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.gamepb.userpb.UserSettingsR\bsettings\".\n" +
	"\x18BatchGetBasicInfoRequest\x12\x12\n" +
	"\x04gids\x18\x01 \x03(\x03R\x04gids\"H\n" +
	"\x16BatchGetBasicInfoReply\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.gamepb.userpb.BasicInfoR\x05users\"=\n" +
	"\vBasicNotify\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x18.gamepb.userpb.BasicInfoR\x05basicBFZDgithub.com/it00021hot/qq-farm-core/internal/farm/proto/userpb;userpbb\x06proto3"

var (
	file_userpb_proto_rawDescOnce sync.Once
	file_userpb_proto_rawDescData []byte
)

func file_userpb_proto_rawDescGZIP() []byte {
	file_userpb_proto_rawDescOnce.Do(func() {
		file_userpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_proto_rawDesc), len(file_userpb_proto_rawDesc)))
	})
	return file_userpb_proto_rawDescData
}

var file_userpb_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_userpb_proto_goTypes = []any{
	(*LoginRequest)(nil),                          // 0: gamepb.userpb.LoginRequest
	(*DeviceInfo)(nil),                            // 1: gamepb.userpb.DeviceInfo
	(*ReportData)(nil),                            // 2: gamepb.userpb.ReportData
	(*LoginReply)(nil),                            // 3: gamepb.userpb.LoginReply
	(*BasicInfo)(nil),                             // 4: gamepb.userpb.BasicInfo
	(*QQGroupInfo)(nil),                           // 5: gamepb.userpb.QQGroupInfo
	(*VersionInfo)(nil),                           // 6: gamepb.userpb.VersionInfo
	(*HeartbeatRequest)(nil),                      // 7: gamepb.userpb.HeartbeatRequest
	(*HeartbeatReply)(nil),                        // 8: gamepb.userpb.HeartbeatReply
	(*ReportArkClickRequest)(nil),                 // 9: gamepb.userpb.ReportArkClickRequest
	(*ReportArkClickReply)(nil),                   // 10: gamepb.userpb.ReportArkClickReply
	(*BatchClientReportFlowRequest)(nil),          // 11: gamepb.userpb.BatchClientReportFlowRequest
	(*ClientFlowItem)(nil),                        // 12: gamepb.userpb.ClientFlowItem
	(*BatchClientReportFlowReply)(nil),            // 13: gamepb.userpb.BatchClientReportFlowReply
	(*SetDisplayInfoRequest)(nil),                 // 14: gamepb.userpb.SetDisplayInfoRequest
	(*SetDisplayInfoReply)(nil),                   // 15: gamepb.userpb.SetDisplayInfoReply
	(*SetQQFriendRecommendAuthorizedRequest)(nil), // 16: gamepb.userpb.SetQQFriendRecommendAuthorizedRequest
	(*SetQQFriendRecommendAuthorizedReply)(nil),   // 17: gamepb.userpb.SetQQFriendRecommendAuthorizedReply
	(*GetUserSettingsRequest)(nil),                // 18: gamepb.userpb.GetUserSettingsRequest
	(*UserSettings)(nil),                          // 19: gamepb.userpb.UserSettings
	(*GetUserSettingsReply)(nil),                  // 20: gamepb.userpb.GetUserSettingsReply
	(*BatchGetBasicInfoRequest)(nil),              // 21: gamepb.userpb.BatchGetBasicInfoRequest
	(*BatchGetBasicInfoReply)(nil),                // 22: gamepb.userpb.BatchGetBasicInfoReply
	(*BasicNotify)(nil),                           // 23: gamepb.userpb.BasicNotify
}
var file_userpb_proto_depIdxs = []int32{
	1,  // 0: gamepb.userpb.LoginRequest.device_info:type_name -> gamepb.userpb.DeviceInfo
	2,  // 1: gamepb.userpb.LoginRequest.report_data:type_name -> gamepb.userpb.ReportData
	4,  // 2: gamepb.userpb.LoginReply.basic:type_name -> gamepb.userpb.BasicInfo
	5,  // 3: gamepb.userpb.LoginReply.qq_group_infos:type_name -> gamepb.userpb.QQGroupInfo
	6,  // 4: gamepb.userpb.LoginReply.version_info:type_name -> gamepb.userpb.VersionInfo
	6,  // 5: gamepb.userpb.HeartbeatReply.version_info:type_name -> gamepb.userpb.VersionInfo
	12, // 6: gamepb.userpb.BatchClientReportFlowRequest.items:type_name -> gamepb.userpb.ClientFlowItem
	4,  // 7: gamepb.userpb.SetDisplayInfoReply.basic:type_name -> gamepb.userpb.BasicInfo
	19, // 8: gamepb.userpb.GetUserSettingsReply.settings:type_name -> gamepb.userpb.UserSettings
	4,  // 9: gamepb.userpb.BatchGetBasicInfoReply.users:type_name -> gamepb.userpb.BasicInfo
	4,  // 10: gamepb.userpb.BasicNotify.basic:type_name -> gamepb.userpb.BasicInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_userpb_proto_init() }
func file_userpb_proto_init() {
	if File_userpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_proto_rawDesc), len(file_userpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userpb_proto_goTypes,
		DependencyIndexes: file_userpb_proto_depIdxs,
		MessageInfos:      file_userpb_proto_msgTypes,
	}.Build()
	File_userpb_proto = out.File
	file_userpb_proto_goTypes = nil
	file_userpb_proto_depIdxs = nil
}
