// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: mallpb.proto

package mallpb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests one mall tab. The client always sends sub_slot_type, including zero.
type GetMallListBySlotTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotType      int32                  `protobuf:"varint,1,opt,name=slot_type,json=slotType,proto3" json:"slot_type,omitempty"`
	SubSlotType   int32                  `protobuf:"varint,2,opt,name=sub_slot_type,json=subSlotType,proto3" json:"sub_slot_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMallListBySlotTypeRequest) Reset() {
	*x = GetMallListBySlotTypeRequest{}
	mi := &file_mallpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMallListBySlotTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMallListBySlotTypeRequest) ProtoMessage() {}

func (x *GetMallListBySlotTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMallListBySlotTypeRequest.ProtoReflect.Descriptor instead.
func (*GetMallListBySlotTypeRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetMallListBySlotTypeRequest) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

func (x *GetMallListBySlotTypeRequest) GetSubSlotType() int32 {
	if x != nil {
		return x.SubSlotType
	}
	return 0
}

// Purchase limits are returned both with a product and after a purchase.
type PurchaseLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LimitType     int32                  `protobuf:"varint,1,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`       // 1=daily, 4=activity-period in the captured products.
	BoughtCount   int32                  `protobuf:"varint,2,opt,name=bought_count,json=boughtCount,proto3" json:"bought_count,omitempty"` // Omitted when zero in a mall-list response.
	LimitCount    int32                  `protobuf:"varint,3,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseLimit) Reset() {
	*x = PurchaseLimit{}
	mi := &file_mallpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseLimit) ProtoMessage() {}

func (x *PurchaseLimit) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseLimit.ProtoReflect.Descriptor instead.
func (*PurchaseLimit) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseLimit) GetLimitType() int32 {
	if x != nil {
		return x.LimitType
	}
	return 0
}

func (x *PurchaseLimit) GetBoughtCount() int32 {
	if x != nil {
		return x.BoughtCount
	}
	return 0
}

func (x *PurchaseLimit) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

type MallGoods struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GoodsId         int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GoodsType       int32                  `protobuf:"varint,3,opt,name=goods_type,json=goodsType,proto3" json:"goods_type,omitempty"`
	RewardItems     []*corepb.Item         `protobuf:"bytes,4,rep,name=reward_items,json=rewardItems,proto3" json:"reward_items,omitempty"`
	Price           *corepb.Item           `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"` // Item ID is the currency; count is the unit price.
	IsFree          bool                   `protobuf:"varint,6,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	PurchaseLimit   *PurchaseLimit         `protobuf:"bytes,7,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	IsLimited       bool                   `protobuf:"varint,8,opt,name=is_limited,json=isLimited,proto3" json:"is_limited,omitempty"`
	DiscountText    string                 `protobuf:"bytes,9,opt,name=discount_text,json=discountText,proto3" json:"discount_text,omitempty"` // Display text such as "7.4折".
	IsDiscounted    bool                   `protobuf:"varint,10,opt,name=is_discounted,json=isDiscounted,proto3" json:"is_discounted,omitempty"`
	DiscountEndTime int64                  `protobuf:"varint,11,opt,name=discount_end_time,json=discountEndTime,proto3" json:"discount_end_time,omitempty"`
	IsAvailable     bool                   `protobuf:"varint,12,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MallGoods) Reset() {
	*x = MallGoods{}
	mi := &file_mallpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MallGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallGoods) ProtoMessage() {}

func (x *MallGoods) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallGoods.ProtoReflect.Descriptor instead.
func (*MallGoods) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{2}
}

func (x *MallGoods) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *MallGoods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MallGoods) GetGoodsType() int32 {
	if x != nil {
		return x.GoodsType
	}
	return 0
}

func (x *MallGoods) GetRewardItems() []*corepb.Item {
	if x != nil {
		return x.RewardItems
	}
	return nil
}

func (x *MallGoods) GetPrice() *corepb.Item {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *MallGoods) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *MallGoods) GetPurchaseLimit() *PurchaseLimit {
	if x != nil {
		return x.PurchaseLimit
	}
	return nil
}

func (x *MallGoods) GetIsLimited() bool {
	if x != nil {
		return x.IsLimited
	}
	return false
}

func (x *MallGoods) GetDiscountText() string {
	if x != nil {
		return x.DiscountText
	}
	return ""
}

func (x *MallGoods) GetIsDiscounted() bool {
	if x != nil {
		return x.IsDiscounted
	}
	return false
}

func (x *MallGoods) GetDiscountEndTime() int64 {
	if x != nil {
		return x.DiscountEndTime
	}
	return 0
}

func (x *MallGoods) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type GetMallListBySlotTypeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoodsList        []*MallGoods           `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
	RefreshCountdown int64                  `protobuf:"varint,2,opt,name=refresh_countdown,json=refreshCountdown,proto3" json:"refresh_countdown,omitempty"` // Seconds until the mall list refreshes.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMallListBySlotTypeResponse) Reset() {
	*x = GetMallListBySlotTypeResponse{}
	mi := &file_mallpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMallListBySlotTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMallListBySlotTypeResponse) ProtoMessage() {}

func (x *GetMallListBySlotTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMallListBySlotTypeResponse.ProtoReflect.Descriptor instead.
func (*GetMallListBySlotTypeResponse) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetMallListBySlotTypeResponse) GetGoodsList() []*MallGoods {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

func (x *GetMallListBySlotTypeResponse) GetRefreshCountdown() int64 {
	if x != nil {
		return x.RefreshCountdown
	}
	return 0
}

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_mallpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *PurchaseRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	RewardItems   []*corepb.Item         `protobuf:"bytes,3,rep,name=reward_items,json=rewardItems,proto3" json:"reward_items,omitempty"`
	PurchaseLimit *PurchaseLimit         `protobuf:"bytes,5,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_mallpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *PurchaseResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PurchaseResponse) GetRewardItems() []*corepb.Item {
	if x != nil {
		return x.RewardItems
	}
	return nil
}

func (x *PurchaseResponse) GetPurchaseLimit() *PurchaseLimit {
	if x != nil {
		return x.PurchaseLimit
	}
	return nil
}

type GetMonthCardInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthCardInfosRequest) Reset() {
	*x = GetMonthCardInfosRequest{}
	mi := &file_mallpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthCardInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthCardInfosRequest) ProtoMessage() {}

func (x *GetMonthCardInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthCardInfosRequest.ProtoReflect.Descriptor instead.
func (*GetMonthCardInfosRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{6}
}

type MonthCardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Reward        *corepb.Item           `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"`
	CanClaim      bool                   `protobuf:"varint,3,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthCardInfo) Reset() {
	*x = MonthCardInfo{}
	mi := &file_mallpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthCardInfo) ProtoMessage() {}

func (x *MonthCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthCardInfo.ProtoReflect.Descriptor instead.
func (*MonthCardInfo) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{7}
}

func (x *MonthCardInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *MonthCardInfo) GetReward() *corepb.Item {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *MonthCardInfo) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

type GetMonthCardInfosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*MonthCardInfo       `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthCardInfosReply) Reset() {
	*x = GetMonthCardInfosReply{}
	mi := &file_mallpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthCardInfosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthCardInfosReply) ProtoMessage() {}

func (x *GetMonthCardInfosReply) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthCardInfosReply.ProtoReflect.Descriptor instead.
func (*GetMonthCardInfosReply) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{8}
}

func (x *GetMonthCardInfosReply) GetInfos() []*MonthCardInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ClaimMonthCardRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMonthCardRewardRequest) Reset() {
	*x = ClaimMonthCardRewardRequest{}
	mi := &file_mallpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMonthCardRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthCardRewardRequest) ProtoMessage() {}

func (x *ClaimMonthCardRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthCardRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimMonthCardRewardRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimMonthCardRewardRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type ClaimMonthCardRewardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMonthCardRewardReply) Reset() {
	*x = ClaimMonthCardRewardReply{}
	mi := &file_mallpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMonthCardRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthCardRewardReply) ProtoMessage() {}

func (x *ClaimMonthCardRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthCardRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimMonthCardRewardReply) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimMonthCardRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProductsHasChangedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotType      int32                  `protobuf:"varint,1,opt,name=slot_type,json=slotType,proto3" json:"slot_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsHasChangedNotify) Reset() {
	*x = ProductsHasChangedNotify{}
	mi := &file_mallpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsHasChangedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsHasChangedNotify) ProtoMessage() {}

func (x *ProductsHasChangedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsHasChangedNotify.ProtoReflect.Descriptor instead.
func (*ProductsHasChangedNotify) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{11}
}

func (x *ProductsHasChangedNotify) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

// Empty in the captured purchase flow. Its presence tells the client to refresh
// any views that depend on the player's current mall needs.
type NeedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedType      int32                  `protobuf:"varint,1,opt,name=need_type,json=needType,proto3" json:"need_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedNotify) Reset() {
	*x = NeedNotify{}
	mi := &file_mallpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedNotify) ProtoMessage() {}

func (x *NeedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedNotify.ProtoReflect.Descriptor instead.
func (*NeedNotify) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{12}
}

func (x *NeedNotify) GetNeedType() int32 {
	if x != nil {
		return x.NeedType
	}
	return 0
}

var File_mallpb_proto protoreflect.FileDescriptor

const file_mallpb_proto_rawDesc = "" +
	"\n" +
	"\fmallpb.proto\x12\rgamepb.mallpb\x1a\fcorepb.proto\"_\n" +
	"\x1cGetMallListBySlotTypeRequest\x12\x1b\n" +
	"\tslot_type\x18\x01 \x01(\x05R\bslotType\x12\"\n" +
	"\rsub_slot_type\x18\x02 \x01(\x05R\vsubSlotType\"r\n" +
	"\rPurchaseLimit\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x01 \x01(\x05R\tlimitType\x12!\n" +
	"\fbought_count\x18\x02 \x01(\x05R\vboughtCount\x12\x1f\n" +
	"\vlimit_count\x18\x03 \x01(\x05R\n" +
	"limitCount\"\xc4\x03\n" +
	"\tMallGoods\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"goods_type\x18\x03 \x01(\x05R\tgoodsType\x12/\n" +
	"\freward_items\x18\x04 \x03(\v2\f.corepb.ItemR\vrewardItems\x12\"\n" +
	"\x05price\x18\x05 \x01(\v2\f.corepb.ItemR\x05price\x12\x17\n" +
	"\ais_free\x18\x06 \x01(\bR\x06isFree\x12C\n" +
	"\x0epurchase_limit\x18\a \x01(\v2\x1c.gamepb.mallpb.PurchaseLimitR\rpurchaseLimit\x12\x1d\n" +
	"\n" +
	"is_limited\x18\b \x01(\bR\tisLimited\x12#\n" +
	"\rdiscount_text\x18\t \x01(\tR\fdiscountText\x12#\n" +
	"\ris_discounted\x18\n" +
	" \x01(\bR\fisDiscounted\x12*\n" +
	"\x11discount_end_time\x18\v \x01(\x03R\x0fdiscountEndTime\x12!\n" +
	"\fis_available\x18\f \x01(\bR\visAvailable\"\x85\x01\n" +
	"\x1dGetMallListBySlotTypeResponse\x127\n" +
	"\n" +
	"goods_list\x18\x01 \x03(\v2\x18.gamepb.mallpb.MallGoodsR\tgoodsList\x12+\n" +
	"\x11refresh_countdown\x18\x02 \x01(\x03R\x10refreshCountdown\"B\n" +
	"\x0fPurchaseRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xb9\x01\n" +
	"\x10PurchaseResponse\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12/\n" +
	"\freward_items\x18\x03 \x03(\v2\f.corepb.ItemR\vrewardItems\x12C\n" +
	"\x0epurchase_limit\x18\x05 \x01(\v2\x1c.gamepb.mallpb.PurchaseLimitR\rpurchaseLimit\"\x1a\n" +
	"\x18GetMonthCardInfosRequest\"m\n" +
	"\rMonthCardInfo\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\x12$\n" +
	"\x06reward\x18\x02 \x01(\v2\f.corepb.ItemR\x06reward\x12\x1b\n" +
	"\tcan_claim\x18\x03 \x01(\bR\bcanClaim\"L\n" +
	"\x16GetMonthCardInfosReply\x122\n" +
	"\x05infos\x18\x01 \x03(\v2\x1c.gamepb.mallpb.MonthCardInfoR\x05infos\"8\n" +
	"\x1bClaimMonthCardRewardRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x05R\agoodsId\"?\n" +
	"\x19ClaimMonthCardRewardReply\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"7\n" +
	"\x18ProductsHasChangedNotify\x12\x1b\n" +
	"\tslot_type\x18\x01 \x01(\x05R\bslotType\")\n" +
	"\n" +
	"NeedNotify\x12\x1b\n" +
	"\tneed_type\x18\x01 \x01(\x05R\bneedType2\xa1\x03\n" +
	"\vMallService\x12r\n" +
	"\x15GetMallListBySlotType\x12+.gamepb.mallpb.GetMallListBySlotTypeRequest\x1a,.gamepb.mallpb.GetMallListBySlotTypeResponse\x12K\n" +
	"\bPurchase\x12\x1e.gamepb.mallpb.PurchaseRequest\x1a\x1f.gamepb.mallpb.PurchaseResponse\x12c\n" +
	"\x11GetMonthCardInfos\x12'.gamepb.mallpb.GetMonthCardInfosRequest\x1a%.gamepb.mallpb.GetMonthCardInfosReply\x12l\n" +
	"\x14ClaimMonthCardReward\x12*.gamepb.mallpb.ClaimMonthCardRewardRequest\x1a(.gamepb.mallpb.ClaimMonthCardRewardReplyBCZAgithub.com/it00021hot/qq-farm-core/internal/farm/proto/mallpb;mallpbb\x06proto3"

var (
	file_mallpb_proto_rawDescOnce sync.Once
	file_mallpb_proto_rawDescData []byte
)

func file_mallpb_proto_rawDescGZIP() []byte {
	file_mallpb_proto_rawDescOnce.Do(func() {
		file_mallpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mallpb_proto_rawDesc), len(file_mallpb_proto_rawDesc)))
	})
	return file_mallpb_proto_rawDescData
}

var file_mallpb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mallpb_proto_goTypes = []any{
	(*GetMallListBySlotTypeRequest)(nil),  // 0: gamepb.mallpb.GetMallListBySlotTypeRequest
	(*PurchaseLimit)(nil),                 // 1: gamepb.mallpb.PurchaseLimit
	(*MallGoods)(nil),                     // 2: gamepb.mallpb.MallGoods
	(*GetMallListBySlotTypeResponse)(nil), // 3: gamepb.mallpb.GetMallListBySlotTypeResponse
	(*PurchaseRequest)(nil),               // 4: gamepb.mallpb.PurchaseRequest
	(*PurchaseResponse)(nil),              // 5: gamepb.mallpb.PurchaseResponse
	(*GetMonthCardInfosRequest)(nil),      // 6: gamepb.mallpb.GetMonthCardInfosRequest
	(*MonthCardInfo)(nil),                 // 7: gamepb.mallpb.MonthCardInfo
	(*GetMonthCardInfosReply)(nil),        // 8: gamepb.mallpb.GetMonthCardInfosReply
	(*ClaimMonthCardRewardRequest)(nil),   // 9: gamepb.mallpb.ClaimMonthCardRewardRequest
	(*ClaimMonthCardRewardReply)(nil),     // 10: gamepb.mallpb.ClaimMonthCardRewardReply
	(*ProductsHasChangedNotify)(nil),      // 11: gamepb.mallpb.ProductsHasChangedNotify
	(*NeedNotify)(nil),                    // 12: gamepb.mallpb.NeedNotify
	(*corepb.Item)(nil),                   // 13: corepb.Item
}
var file_mallpb_proto_depIdxs = []int32{
	13, // 0: gamepb.mallpb.MallGoods.reward_items:type_name -> corepb.Item
	13, // 1: gamepb.mallpb.MallGoods.price:type_name -> corepb.Item
	1,  // 2: gamepb.mallpb.MallGoods.purchase_limit:type_name -> gamepb.mallpb.PurchaseLimit
	2,  // 3: gamepb.mallpb.GetMallListBySlotTypeResponse.goods_list:type_name -> gamepb.mallpb.MallGoods
	13, // 4: gamepb.mallpb.PurchaseResponse.reward_items:type_name -> corepb.Item
	1,  // 5: gamepb.mallpb.PurchaseResponse.purchase_limit:type_name -> gamepb.mallpb.PurchaseLimit
	13, // 6: gamepb.mallpb.MonthCardInfo.reward:type_name -> corepb.Item
	7,  // 7: gamepb.mallpb.GetMonthCardInfosReply.infos:type_name -> gamepb.mallpb.MonthCardInfo
	13, // 8: gamepb.mallpb.ClaimMonthCardRewardReply.items:type_name -> corepb.Item
	0,  // 9: gamepb.mallpb.MallService.GetMallListBySlotType:input_type -> gamepb.mallpb.GetMallListBySlotTypeRequest
	4,  // 10: gamepb.mallpb.MallService.Purchase:input_type -> gamepb.mallpb.PurchaseRequest
	6,  // 11: gamepb.mallpb.MallService.GetMonthCardInfos:input_type -> gamepb.mallpb.GetMonthCardInfosRequest
	9,  // 12: gamepb.mallpb.MallService.ClaimMonthCardReward:input_type -> gamepb.mallpb.ClaimMonthCardRewardRequest
	3,  // 13: gamepb.mallpb.MallService.GetMallListBySlotType:output_type -> gamepb.mallpb.GetMallListBySlotTypeResponse
	5,  // 14: gamepb.mallpb.MallService.Purchase:output_type -> gamepb.mallpb.PurchaseResponse
	8,  // 15: gamepb.mallpb.MallService.GetMonthCardInfos:output_type -> gamepb.mallpb.GetMonthCardInfosReply
	10, // 16: gamepb.mallpb.MallService.ClaimMonthCardReward:output_type -> gamepb.mallpb.ClaimMonthCardRewardReply
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mallpb_proto_init() }
func file_mallpb_proto_init() {
	if File_mallpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mallpb_proto_rawDesc), len(file_mallpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mallpb_proto_goTypes,
		DependencyIndexes: file_mallpb_proto_depIdxs,
		MessageInfos:      file_mallpb_proto_msgTypes,
	}.Build()
	File_mallpb_proto = out.File
	file_mallpb_proto_goTypes = nil
	file_mallpb_proto_depIdxs = nil
}
