// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sharepb.proto

package sharepb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 检查是否可以分享 ---
type CheckCanShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCanShareRequest) Reset() {
	*x = CheckCanShareRequest{}
	mi := &file_sharepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCanShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanShareRequest) ProtoMessage() {}

func (x *CheckCanShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanShareRequest.ProtoReflect.Descriptor instead.
func (*CheckCanShareRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{0}
}

type CheckCanShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanShare      bool                   `protobuf:"varint,1,opt,name=can_share,json=canShare,proto3" json:"can_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCanShareReply) Reset() {
	*x = CheckCanShareReply{}
	mi := &file_sharepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCanShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanShareReply) ProtoMessage() {}

func (x *CheckCanShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanShareReply.ProtoReflect.Descriptor instead.
func (*CheckCanShareReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCanShareReply) GetCanShare() bool {
	if x != nil {
		return x.CanShare
	}
	return false
}

// --- 分享上报（抓包确认：field_1=true，field_4=42） ---
type ReportShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field_1       bool                   `protobuf:"varint,1,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
	Field_4       int32                  `protobuf:"varint,4,opt,name=field_4,json=field4,proto3" json:"field_4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportShareRequest) Reset() {
	*x = ReportShareRequest{}
	mi := &file_sharepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportShareRequest) ProtoMessage() {}

func (x *ReportShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportShareRequest.ProtoReflect.Descriptor instead.
func (*ReportShareRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{2}
}

func (x *ReportShareRequest) GetField_1() bool {
	if x != nil {
		return x.Field_1
	}
	return false
}

func (x *ReportShareRequest) GetField_4() int32 {
	if x != nil {
		return x.Field_4
	}
	return 0
}

type ReportShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportShareReply) Reset() {
	*x = ReportShareReply{}
	mi := &file_sharepb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportShareReply) ProtoMessage() {}

func (x *ReportShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportShareReply.ProtoReflect.Descriptor instead.
func (*ReportShareReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{3}
}

func (x *ReportShareReply) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// --- 分享奖励（抓包确认：field_1=true） ---
type ClaimShareRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field_1       bool                   `protobuf:"varint,1,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimShareRewardRequest) Reset() {
	*x = ClaimShareRewardRequest{}
	mi := &file_sharepb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimShareRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimShareRewardRequest) ProtoMessage() {}

func (x *ClaimShareRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimShareRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimShareRewardRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimShareRewardRequest) GetField_1() bool {
	if x != nil {
		return x.Field_1
	}
	return false
}

type ClaimShareRewardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimShareRewardReply) Reset() {
	*x = ClaimShareRewardReply{}
	mi := &file_sharepb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimShareRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimShareRewardReply) ProtoMessage() {}

func (x *ClaimShareRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimShareRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimShareRewardReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimShareRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// --- 获取邀请信息 ---
type GetInviteInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteInfoRequest) Reset() {
	*x = GetInviteInfoRequest{}
	mi := &file_sharepb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteInfoRequest) ProtoMessage() {}

func (x *GetInviteInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInviteInfoRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{6}
}

type InviteUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Field_2       int64                  `protobuf:"varint,2,opt,name=field_2,json=field2,proto3" json:"field_2,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUser) Reset() {
	*x = InviteUser{}
	mi := &file_sharepb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUser) ProtoMessage() {}

func (x *InviteUser) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUser.ProtoReflect.Descriptor instead.
func (*InviteUser) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{7}
}

func (x *InviteUser) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *InviteUser) GetField_2() int64 {
	if x != nil {
		return x.Field_2
	}
	return 0
}

func (x *InviteUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InviteUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type InviteRewardStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	RewardIndex   int64                  `protobuf:"varint,2,opt,name=reward_index,json=rewardIndex,proto3" json:"reward_index,omitempty"`
	Item          *corepb.Item           `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRewardStage) Reset() {
	*x = InviteRewardStage{}
	mi := &file_sharepb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRewardStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardStage) ProtoMessage() {}

func (x *InviteRewardStage) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardStage.ProtoReflect.Descriptor instead.
func (*InviteRewardStage) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{8}
}

func (x *InviteRewardStage) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InviteRewardStage) GetRewardIndex() int64 {
	if x != nil {
		return x.RewardIndex
	}
	return 0
}

func (x *InviteRewardStage) GetItem() *corepb.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *InviteRewardStage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type InviteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserA         *InviteUser            `protobuf:"bytes,1,opt,name=user_a,json=userA,proto3" json:"user_a,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	UserB         *InviteUser            `protobuf:"bytes,3,opt,name=user_b,json=userB,proto3" json:"user_b,omitempty"`
	RewardStages  []*InviteRewardStage   `protobuf:"bytes,4,rep,name=reward_stages,json=rewardStages,proto3" json:"reward_stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteInfo) Reset() {
	*x = InviteInfo{}
	mi := &file_sharepb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteInfo) ProtoMessage() {}

func (x *InviteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteInfo.ProtoReflect.Descriptor instead.
func (*InviteInfo) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{9}
}

func (x *InviteInfo) GetUserA() *InviteUser {
	if x != nil {
		return x.UserA
	}
	return nil
}

func (x *InviteInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InviteInfo) GetUserB() *InviteUser {
	if x != nil {
		return x.UserB
	}
	return nil
}

func (x *InviteInfo) GetRewardStages() []*InviteRewardStage {
	if x != nil {
		return x.RewardStages
	}
	return nil
}

type GetInviteInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*InviteInfo          `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteInfoReply) Reset() {
	*x = GetInviteInfoReply{}
	mi := &file_sharepb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteInfoReply) ProtoMessage() {}

func (x *GetInviteInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteInfoReply.ProtoReflect.Descriptor instead.
func (*GetInviteInfoReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{10}
}

func (x *GetInviteInfoReply) GetInfos() []*InviteInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// --- 领取邀请奖励 ---
type GetInviteAwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareCfgId    int64                  `protobuf:"varint,1,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteAwardRequest) Reset() {
	*x = GetInviteAwardRequest{}
	mi := &file_sharepb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteAwardRequest) ProtoMessage() {}

func (x *GetInviteAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteAwardRequest.ProtoReflect.Descriptor instead.
func (*GetInviteAwardRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{11}
}

func (x *GetInviteAwardRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

type GetInviteAwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Items         []*corepb.Item         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteAwardReply) Reset() {
	*x = GetInviteAwardReply{}
	mi := &file_sharepb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteAwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteAwardReply) ProtoMessage() {}

func (x *GetInviteAwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteAwardReply.ProtoReflect.Descriptor instead.
func (*GetInviteAwardReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{12}
}

func (x *GetInviteAwardReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInviteAwardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_sharepb_proto protoreflect.FileDescriptor

const file_sharepb_proto_rawDesc = "" +
	"\n" +
	"\rsharepb.proto\x12\x0egamepb.sharepb\x1a\fcorepb.proto\"\x16\n" +
	"\x14CheckCanShareRequest\"1\n" +
	"\x12CheckCanShareReply\x12\x1b\n" +
	"\tcan_share\x18\x01 \x01(\bR\bcanShare\"F\n" +
	"\x12ReportShareRequest\x12\x17\n" +
	"\afield_1\x18\x01 \x01(\bR\x06field1\x12\x17\n" +
	"\afield_4\x18\x04 \x01(\x05R\x06field4\"*\n" +
	"\x10ReportShareReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"2\n" +
	"\x17ClaimShareRewardRequest\x12\x17\n" +
	"\afield_1\x18\x01 \x01(\bR\x06field1\";\n" +
	"\x15ClaimShareRewardReply\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"\x16\n" +
	"\x14GetInviteInfoRequest\"c\n" +
	"\n" +
	"InviteUser\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x17\n" +
	"\afield_2\x18\x02 \x01(\x03R\x06field2\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x86\x01\n" +
	"\x11InviteRewardStage\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12!\n" +
	"\freward_index\x18\x02 \x01(\x03R\vrewardIndex\x12 \n" +
	"\x04item\x18\x03 \x01(\v2\f.corepb.ItemR\x04item\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xd2\x01\n" +
	"\n" +
	"InviteInfo\x121\n" +
	"\x06user_a\x18\x01 \x01(\v2\x1a.gamepb.sharepb.InviteUserR\x05userA\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x121\n" +
	"\x06user_b\x18\x03 \x01(\v2\x1a.gamepb.sharepb.InviteUserR\x05userB\x12F\n" +
	"\rreward_stages\x18\x04 \x03(\v2!.gamepb.sharepb.InviteRewardStageR\frewardStages\"F\n" +
	"\x12GetInviteInfoReply\x120\n" +
	"\x05infos\x18\x01 \x03(\v2\x1a.gamepb.sharepb.InviteInfoR\x05infos\"9\n" +
	"\x15GetInviteAwardRequest\x12 \n" +
	"\fshare_cfg_id\x18\x01 \x01(\x03R\n" +
	"shareCfgId\"S\n" +
	"\x13GetInviteAwardReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.corepb.ItemR\x05itemsBEZCgithub.com/it00021hot/qq-farm-core/internal/farm/proto/sharepb;sharepbb\x06proto3"

var (
	file_sharepb_proto_rawDescOnce sync.Once
	file_sharepb_proto_rawDescData []byte
)

func file_sharepb_proto_rawDescGZIP() []byte {
	file_sharepb_proto_rawDescOnce.Do(func() {
		file_sharepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharepb_proto_rawDesc), len(file_sharepb_proto_rawDesc)))
	})
	return file_sharepb_proto_rawDescData
}

var file_sharepb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sharepb_proto_goTypes = []any{
	(*CheckCanShareRequest)(nil),    // 0: gamepb.sharepb.CheckCanShareRequest
	(*CheckCanShareReply)(nil),      // 1: gamepb.sharepb.CheckCanShareReply
	(*ReportShareRequest)(nil),      // 2: gamepb.sharepb.ReportShareRequest
	(*ReportShareReply)(nil),        // 3: gamepb.sharepb.ReportShareReply
	(*ClaimShareRewardRequest)(nil), // 4: gamepb.sharepb.ClaimShareRewardRequest
	(*ClaimShareRewardReply)(nil),   // 5: gamepb.sharepb.ClaimShareRewardReply
	(*GetInviteInfoRequest)(nil),    // 6: gamepb.sharepb.GetInviteInfoRequest
	(*InviteUser)(nil),              // 7: gamepb.sharepb.InviteUser
	(*InviteRewardStage)(nil),       // 8: gamepb.sharepb.InviteRewardStage
	(*InviteInfo)(nil),              // 9: gamepb.sharepb.InviteInfo
	(*GetInviteInfoReply)(nil),      // 10: gamepb.sharepb.GetInviteInfoReply
	(*GetInviteAwardRequest)(nil),   // 11: gamepb.sharepb.GetInviteAwardRequest
	(*GetInviteAwardReply)(nil),     // 12: gamepb.sharepb.GetInviteAwardReply
	(*corepb.Item)(nil),             // 13: corepb.Item
}
var file_sharepb_proto_depIdxs = []int32{
	13, // 0: gamepb.sharepb.ClaimShareRewardReply.items:type_name -> corepb.Item
	13, // 1: gamepb.sharepb.InviteRewardStage.item:type_name -> corepb.Item
	7,  // 2: gamepb.sharepb.InviteInfo.user_a:type_name -> gamepb.sharepb.InviteUser
	7,  // 3: gamepb.sharepb.InviteInfo.user_b:type_name -> gamepb.sharepb.InviteUser
	8,  // 4: gamepb.sharepb.InviteInfo.reward_stages:type_name -> gamepb.sharepb.InviteRewardStage
	9,  // 5: gamepb.sharepb.GetInviteInfoReply.infos:type_name -> gamepb.sharepb.InviteInfo
	13, // 6: gamepb.sharepb.GetInviteAwardReply.items:type_name -> corepb.Item
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sharepb_proto_init() }
func file_sharepb_proto_init() {
	if File_sharepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharepb_proto_rawDesc), len(file_sharepb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sharepb_proto_goTypes,
		DependencyIndexes: file_sharepb_proto_depIdxs,
		MessageInfos:      file_sharepb_proto_msgTypes,
	}.Build()
	File_sharepb_proto = out.File
	file_sharepb_proto_goTypes = nil
	file_sharepb_proto_depIdxs = nil
}
