// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: uicproxypb.proto

package uicproxypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 文本审核结果 ============
type TextResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 审核状态
	Text   string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`      // 审核后的文本
	// field 3 reserved
	Uid           string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResult) Reset() {
	*x = TextResult{}
	mi := &file_uicproxypb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResult) ProtoMessage() {}

func (x *TextResult) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResult.ProtoReflect.Descriptor instead.
func (*TextResult) Descriptor() ([]byte, []int) {
	return file_uicproxypb_proto_rawDescGZIP(), []int{0}
}

func (x *TextResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TextResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResult) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// ============ 请求/回复 ============
type TextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_uicproxypb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_uicproxypb_proto_rawDescGZIP(), []int{1}
}

func (x *TextItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BatchModerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TextItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModerateTextRequest) Reset() {
	*x = BatchModerateTextRequest{}
	mi := &file_uicproxypb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModerateTextRequest) ProtoMessage() {}

func (x *BatchModerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModerateTextRequest.ProtoReflect.Descriptor instead.
func (*BatchModerateTextRequest) Descriptor() ([]byte, []int) {
	return file_uicproxypb_proto_rawDescGZIP(), []int{2}
}

func (x *BatchModerateTextRequest) GetItems() []*TextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchModerateTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TextResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModerateTextReply) Reset() {
	*x = BatchModerateTextReply{}
	mi := &file_uicproxypb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModerateTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModerateTextReply) ProtoMessage() {}

func (x *BatchModerateTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModerateTextReply.ProtoReflect.Descriptor instead.
func (*BatchModerateTextReply) Descriptor() ([]byte, []int) {
	return file_uicproxypb_proto_rawDescGZIP(), []int{3}
}

func (x *BatchModerateTextReply) GetResults() []*TextResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_uicproxypb_proto protoreflect.FileDescriptor

const file_uicproxypb_proto_rawDesc = "" +
	"\n" +
	"\x10uicproxypb.proto\x12\x11gamepb.uicproxypb\"J\n" +
	"\n" +
	"TextResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\"0\n" +
	"\bTextItem\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"M\n" +
	"\x18BatchModerateTextRequest\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.gamepb.uicproxypb.TextItemR\x05items\"Q\n" +
	"\x16BatchModerateTextReply\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.gamepb.uicproxypb.TextResultR\aresultsBKZIgithub.com/it00021hot/qq-farm-core/internal/farm/proto/uicproxypb;uicproxypbb\x06proto3"

var (
	file_uicproxypb_proto_rawDescOnce sync.Once
	file_uicproxypb_proto_rawDescData []byte
)

func file_uicproxypb_proto_rawDescGZIP() []byte {
	file_uicproxypb_proto_rawDescOnce.Do(func() {
		file_uicproxypb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uicproxypb_proto_rawDesc), len(file_uicproxypb_proto_rawDesc)))
	})
	return file_uicproxypb_proto_rawDescData
}

var file_uicproxypb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_uicproxypb_proto_goTypes = []any{
	(*TextResult)(nil),               // 0: gamepb.uicproxypb.TextResult
	(*TextItem)(nil),                 // 1: gamepb.uicproxypb.TextItem
	(*BatchModerateTextRequest)(nil), // 2: gamepb.uicproxypb.BatchModerateTextRequest
	(*BatchModerateTextReply)(nil),   // 3: gamepb.uicproxypb.BatchModerateTextReply
}
var file_uicproxypb_proto_depIdxs = []int32{
	1, // 0: gamepb.uicproxypb.BatchModerateTextRequest.items:type_name -> gamepb.uicproxypb.TextItem
	0, // 1: gamepb.uicproxypb.BatchModerateTextReply.results:type_name -> gamepb.uicproxypb.TextResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_uicproxypb_proto_init() }
func file_uicproxypb_proto_init() {
	if File_uicproxypb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uicproxypb_proto_rawDesc), len(file_uicproxypb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uicproxypb_proto_goTypes,
		DependencyIndexes: file_uicproxypb_proto_depIdxs,
		MessageInfos:      file_uicproxypb_proto_msgTypes,
	}.Build()
	File_uicproxypb_proto = out.File
	file_uicproxypb_proto_goTypes = nil
	file_uicproxypb_proto_depIdxs = nil
}
