// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/MQEnergy/go-skeleton/internal/app/model"
)

func newAuthResource(db *gorm.DB, opts ...gen.DOOption) authResource {
	_authResource := authResource{}

	_authResource.authResourceDo.UseDB(db, opts...)
	_authResource.authResourceDo.UseModel(&model.AuthResource{})

	tableName := _authResource.authResourceDo.TableName()
	_authResource.ALL = field.NewAsterisk(tableName)
	_authResource.ID = field.NewUint64(tableName, "id")
	_authResource.Name = field.NewString(tableName, "name")
	_authResource.Alias_ = field.NewString(tableName, "alias")
	_authResource.Desc = field.NewString(tableName, "desc")
	_authResource.FURL = field.NewString(tableName, "f_url")
	_authResource.BURL = field.NewString(tableName, "b_url")
	_authResource.Icon = field.NewString(tableName, "icon")
	_authResource.ParentID = field.NewUint64(tableName, "parent_id")
	_authResource.Path = field.NewString(tableName, "path")
	_authResource.SType = field.NewInt8(tableName, "s_type")
	_authResource.Status = field.NewUint8(tableName, "status")
	_authResource.SortOrder = field.NewUint16(tableName, "sort_order")
	_authResource.CreatedAt = field.NewInt64(tableName, "created_at")
	_authResource.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_authResource.fillFieldMap()

	return _authResource
}

type authResource struct {
	authResourceDo

	ALL       field.Asterisk
	ID        field.Uint64
	Name      field.String // 资源名称
	Alias_    field.String // 资源别名
	Desc      field.String // 资源描述
	FURL      field.String // 资源前端URL
	BURL      field.String // 资源后端URL
	Icon      field.String // 资源icon
	ParentID  field.Uint64 // 父级ID
	Path      field.String // ID路径 1-2-3...
	SType     field.Int8   // 资源类型 1：模块 2：操作
	Status    field.Uint8  // 状态：1正常(默认) 2停用
	SortOrder field.Uint16 // 排序
	CreatedAt field.Int64
	UpdatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (a authResource) Table(newTableName string) *authResource {
	a.authResourceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authResource) As(alias string) *authResource {
	a.authResourceDo.DO = *(a.authResourceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authResource) updateTableName(table string) *authResource {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Alias_ = field.NewString(table, "alias")
	a.Desc = field.NewString(table, "desc")
	a.FURL = field.NewString(table, "f_url")
	a.BURL = field.NewString(table, "b_url")
	a.Icon = field.NewString(table, "icon")
	a.ParentID = field.NewUint64(table, "parent_id")
	a.Path = field.NewString(table, "path")
	a.SType = field.NewInt8(table, "s_type")
	a.Status = field.NewUint8(table, "status")
	a.SortOrder = field.NewUint16(table, "sort_order")
	a.CreatedAt = field.NewInt64(table, "created_at")
	a.UpdatedAt = field.NewInt64(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authResource) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["alias"] = a.Alias_
	a.fieldMap["desc"] = a.Desc
	a.fieldMap["f_url"] = a.FURL
	a.fieldMap["b_url"] = a.BURL
	a.fieldMap["icon"] = a.Icon
	a.fieldMap["parent_id"] = a.ParentID
	a.fieldMap["path"] = a.Path
	a.fieldMap["s_type"] = a.SType
	a.fieldMap["status"] = a.Status
	a.fieldMap["sort_order"] = a.SortOrder
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authResource) clone(db *gorm.DB) authResource {
	a.authResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authResource) replaceDB(db *gorm.DB) authResource {
	a.authResourceDo.ReplaceDB(db)
	return a
}

type authResourceDo struct{ gen.DO }

type IAuthResourceDo interface {
	gen.SubQuery
	Debug() IAuthResourceDo
	WithContext(ctx context.Context) IAuthResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthResourceDo
	WriteDB() IAuthResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthResourceDo
	Not(conds ...gen.Condition) IAuthResourceDo
	Or(conds ...gen.Condition) IAuthResourceDo
	Select(conds ...field.Expr) IAuthResourceDo
	Where(conds ...gen.Condition) IAuthResourceDo
	Order(conds ...field.Expr) IAuthResourceDo
	Distinct(cols ...field.Expr) IAuthResourceDo
	Omit(cols ...field.Expr) IAuthResourceDo
	Join(table schema.Tabler, on ...field.Expr) IAuthResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthResourceDo
	Group(cols ...field.Expr) IAuthResourceDo
	Having(conds ...gen.Condition) IAuthResourceDo
	Limit(limit int) IAuthResourceDo
	Offset(offset int) IAuthResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthResourceDo
	Unscoped() IAuthResourceDo
	Create(values ...*model.AuthResource) error
	CreateInBatches(values []*model.AuthResource, batchSize int) error
	Save(values ...*model.AuthResource) error
	First() (*model.AuthResource, error)
	Take() (*model.AuthResource, error)
	Last() (*model.AuthResource, error)
	Find() ([]*model.AuthResource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthResource, err error)
	FindInBatches(result *[]*model.AuthResource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthResource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthResourceDo
	Assign(attrs ...field.AssignExpr) IAuthResourceDo
	Joins(fields ...field.RelationField) IAuthResourceDo
	Preload(fields ...field.RelationField) IAuthResourceDo
	FirstOrInit() (*model.AuthResource, error)
	FirstOrCreate() (*model.AuthResource, error)
	FindByPage(offset int, limit int) (result []*model.AuthResource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authResourceDo) Debug() IAuthResourceDo {
	return a.withDO(a.DO.Debug())
}

func (a authResourceDo) WithContext(ctx context.Context) IAuthResourceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authResourceDo) ReadDB() IAuthResourceDo {
	return a.Clauses(dbresolver.Read)
}

func (a authResourceDo) WriteDB() IAuthResourceDo {
	return a.Clauses(dbresolver.Write)
}

func (a authResourceDo) Session(config *gorm.Session) IAuthResourceDo {
	return a.withDO(a.DO.Session(config))
}

func (a authResourceDo) Clauses(conds ...clause.Expression) IAuthResourceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authResourceDo) Returning(value interface{}, columns ...string) IAuthResourceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authResourceDo) Not(conds ...gen.Condition) IAuthResourceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authResourceDo) Or(conds ...gen.Condition) IAuthResourceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authResourceDo) Select(conds ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authResourceDo) Where(conds ...gen.Condition) IAuthResourceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authResourceDo) Order(conds ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authResourceDo) Distinct(cols ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authResourceDo) Omit(cols ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authResourceDo) Join(table schema.Tabler, on ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authResourceDo) Group(cols ...field.Expr) IAuthResourceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authResourceDo) Having(conds ...gen.Condition) IAuthResourceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authResourceDo) Limit(limit int) IAuthResourceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authResourceDo) Offset(offset int) IAuthResourceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthResourceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authResourceDo) Unscoped() IAuthResourceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authResourceDo) Create(values ...*model.AuthResource) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authResourceDo) CreateInBatches(values []*model.AuthResource, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authResourceDo) Save(values ...*model.AuthResource) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authResourceDo) First() (*model.AuthResource, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthResource), nil
	}
}

func (a authResourceDo) Take() (*model.AuthResource, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthResource), nil
	}
}

func (a authResourceDo) Last() (*model.AuthResource, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthResource), nil
	}
}

func (a authResourceDo) Find() ([]*model.AuthResource, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthResource), err
}

func (a authResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthResource, err error) {
	buf := make([]*model.AuthResource, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authResourceDo) FindInBatches(result *[]*model.AuthResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authResourceDo) Attrs(attrs ...field.AssignExpr) IAuthResourceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authResourceDo) Assign(attrs ...field.AssignExpr) IAuthResourceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authResourceDo) Joins(fields ...field.RelationField) IAuthResourceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authResourceDo) Preload(fields ...field.RelationField) IAuthResourceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authResourceDo) FirstOrInit() (*model.AuthResource, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthResource), nil
	}
}

func (a authResourceDo) FirstOrCreate() (*model.AuthResource, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthResource), nil
	}
}

func (a authResourceDo) FindByPage(offset int, limit int) (result []*model.AuthResource, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authResourceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authResourceDo) Delete(models ...*model.AuthResource) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authResourceDo) withDO(do gen.Dao) *authResourceDo {
	a.DO = *do.(*gen.DO)
	return a
}
