// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Attachment    *attachment
	SysAdmin      *sysAdmin
	SysCasbinRule *sysCasbinRule
	SysResource   *sysResource
	SysRole       *sysRole
	SysRoleAuth   *sysRoleAuth
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Attachment = &Q.Attachment
	SysAdmin = &Q.SysAdmin
	SysCasbinRule = &Q.SysCasbinRule
	SysResource = &Q.SysResource
	SysRole = &Q.SysRole
	SysRoleAuth = &Q.SysRoleAuth
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Attachment:    newAttachment(db, opts...),
		SysAdmin:      newSysAdmin(db, opts...),
		SysCasbinRule: newSysCasbinRule(db, opts...),
		SysResource:   newSysResource(db, opts...),
		SysRole:       newSysRole(db, opts...),
		SysRoleAuth:   newSysRoleAuth(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Attachment    attachment
	SysAdmin      sysAdmin
	SysCasbinRule sysCasbinRule
	SysResource   sysResource
	SysRole       sysRole
	SysRoleAuth   sysRoleAuth
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Attachment:    q.Attachment.clone(db),
		SysAdmin:      q.SysAdmin.clone(db),
		SysCasbinRule: q.SysCasbinRule.clone(db),
		SysResource:   q.SysResource.clone(db),
		SysRole:       q.SysRole.clone(db),
		SysRoleAuth:   q.SysRoleAuth.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Attachment:    q.Attachment.replaceDB(db),
		SysAdmin:      q.SysAdmin.replaceDB(db),
		SysCasbinRule: q.SysCasbinRule.replaceDB(db),
		SysResource:   q.SysResource.replaceDB(db),
		SysRole:       q.SysRole.replaceDB(db),
		SysRoleAuth:   q.SysRoleAuth.replaceDB(db),
	}
}

type queryCtx struct {
	Attachment    IAttachmentDo
	SysAdmin      ISysAdminDo
	SysCasbinRule ISysCasbinRuleDo
	SysResource   ISysResourceDo
	SysRole       ISysRoleDo
	SysRoleAuth   ISysRoleAuthDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Attachment:    q.Attachment.WithContext(ctx),
		SysAdmin:      q.SysAdmin.WithContext(ctx),
		SysCasbinRule: q.SysCasbinRule.WithContext(ctx),
		SysResource:   q.SysResource.WithContext(ctx),
		SysRole:       q.SysRole.WithContext(ctx),
		SysRoleAuth:   q.SysRoleAuth.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
