// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bulletinboardpb.proto

package bulletinboardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 公告信息 ============
type BulletinItem struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 1=已读
	// field 4 reserved
	Type          int64 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletinItem) Reset() {
	*x = BulletinItem{}
	mi := &file_bulletinboardpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletinItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletinItem) ProtoMessage() {}

func (x *BulletinItem) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletinItem.ProtoReflect.Descriptor instead.
func (*BulletinItem) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{0}
}

func (x *BulletinItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BulletinItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BulletinItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BulletinItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

// ============ 请求/回复 ============
type GetBulletinListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 获取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulletinListRequest) Reset() {
	*x = GetBulletinListRequest{}
	mi := &file_bulletinboardpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulletinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulletinListRequest) ProtoMessage() {}

func (x *GetBulletinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulletinListRequest.ProtoReflect.Descriptor instead.
func (*GetBulletinListRequest) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetBulletinListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetBulletinListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bulletins     []*BulletinItem        `protobuf:"bytes,1,rep,name=bulletins,proto3" json:"bulletins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulletinListReply) Reset() {
	*x = GetBulletinListReply{}
	mi := &file_bulletinboardpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulletinListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulletinListReply) ProtoMessage() {}

func (x *GetBulletinListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulletinListReply.ProtoReflect.Descriptor instead.
func (*GetBulletinListReply) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetBulletinListReply) GetBulletins() []*BulletinItem {
	if x != nil {
		return x.Bulletins
	}
	return nil
}

// --- 获取公告详情 ---
type GetBulletinDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 公告ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulletinDetailRequest) Reset() {
	*x = GetBulletinDetailRequest{}
	mi := &file_bulletinboardpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulletinDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulletinDetailRequest) ProtoMessage() {}

func (x *GetBulletinDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulletinDetailRequest.ProtoReflect.Descriptor instead.
func (*GetBulletinDetailRequest) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetBulletinDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BulletinDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 公告内容
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Type          int64                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // 其他字段待逆向确认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletinDetail) Reset() {
	*x = BulletinDetail{}
	mi := &file_bulletinboardpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletinDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletinDetail) ProtoMessage() {}

func (x *BulletinDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletinDetail.ProtoReflect.Descriptor instead.
func (*BulletinDetail) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{4}
}

func (x *BulletinDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BulletinDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BulletinDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BulletinDetail) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BulletinDetail) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetBulletinDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *BulletinDetail        `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulletinDetailReply) Reset() {
	*x = GetBulletinDetailReply{}
	mi := &file_bulletinboardpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulletinDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulletinDetailReply) ProtoMessage() {}

func (x *GetBulletinDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulletinDetailReply.ProtoReflect.Descriptor instead.
func (*GetBulletinDetailReply) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetBulletinDetailReply) GetDetail() *BulletinDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// ============ 通知 ============
type BulletinListChangedNTF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bulletins     []*BulletinItem        `protobuf:"bytes,1,rep,name=bulletins,proto3" json:"bulletins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletinListChangedNTF) Reset() {
	*x = BulletinListChangedNTF{}
	mi := &file_bulletinboardpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletinListChangedNTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletinListChangedNTF) ProtoMessage() {}

func (x *BulletinListChangedNTF) ProtoReflect() protoreflect.Message {
	mi := &file_bulletinboardpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletinListChangedNTF.ProtoReflect.Descriptor instead.
func (*BulletinListChangedNTF) Descriptor() ([]byte, []int) {
	return file_bulletinboardpb_proto_rawDescGZIP(), []int{6}
}

func (x *BulletinListChangedNTF) GetBulletins() []*BulletinItem {
	if x != nil {
		return x.Bulletins
	}
	return nil
}

var File_bulletinboardpb_proto protoreflect.FileDescriptor

const file_bulletinboardpb_proto_rawDesc = "" +
	"\n" +
	"\x15bulletinboardpb.proto\x12\x16gamepb.bulletinboardpb\"`\n" +
	"\fBulletinItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\".\n" +
	"\x16GetBulletinListRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"Z\n" +
	"\x14GetBulletinListReply\x12B\n" +
	"\tbulletins\x18\x01 \x03(\v2$.gamepb.bulletinboardpb.BulletinItemR\tbulletins\"*\n" +
	"\x18GetBulletinDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"|\n" +
	"\x0eBulletinDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\"X\n" +
	"\x16GetBulletinDetailReply\x12>\n" +
	"\x06detail\x18\x01 \x01(\v2&.gamepb.bulletinboardpb.BulletinDetailR\x06detail\"\\\n" +
	"\x16BulletinListChangedNTF\x12B\n" +
	"\tbulletins\x18\x01 \x03(\v2$.gamepb.bulletinboardpb.BulletinItemR\tbulletinsBUZSgithub.com/MQEnergy/go-skeleton/internal/farm/proto/bulletinboardpb;bulletinboardpbb\x06proto3"

var (
	file_bulletinboardpb_proto_rawDescOnce sync.Once
	file_bulletinboardpb_proto_rawDescData []byte
)

func file_bulletinboardpb_proto_rawDescGZIP() []byte {
	file_bulletinboardpb_proto_rawDescOnce.Do(func() {
		file_bulletinboardpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bulletinboardpb_proto_rawDesc), len(file_bulletinboardpb_proto_rawDesc)))
	})
	return file_bulletinboardpb_proto_rawDescData
}

var file_bulletinboardpb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bulletinboardpb_proto_goTypes = []any{
	(*BulletinItem)(nil),             // 0: gamepb.bulletinboardpb.BulletinItem
	(*GetBulletinListRequest)(nil),   // 1: gamepb.bulletinboardpb.GetBulletinListRequest
	(*GetBulletinListReply)(nil),     // 2: gamepb.bulletinboardpb.GetBulletinListReply
	(*GetBulletinDetailRequest)(nil), // 3: gamepb.bulletinboardpb.GetBulletinDetailRequest
	(*BulletinDetail)(nil),           // 4: gamepb.bulletinboardpb.BulletinDetail
	(*GetBulletinDetailReply)(nil),   // 5: gamepb.bulletinboardpb.GetBulletinDetailReply
	(*BulletinListChangedNTF)(nil),   // 6: gamepb.bulletinboardpb.BulletinListChangedNTF
}
var file_bulletinboardpb_proto_depIdxs = []int32{
	0, // 0: gamepb.bulletinboardpb.GetBulletinListReply.bulletins:type_name -> gamepb.bulletinboardpb.BulletinItem
	4, // 1: gamepb.bulletinboardpb.GetBulletinDetailReply.detail:type_name -> gamepb.bulletinboardpb.BulletinDetail
	0, // 2: gamepb.bulletinboardpb.BulletinListChangedNTF.bulletins:type_name -> gamepb.bulletinboardpb.BulletinItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bulletinboardpb_proto_init() }
func file_bulletinboardpb_proto_init() {
	if File_bulletinboardpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bulletinboardpb_proto_rawDesc), len(file_bulletinboardpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bulletinboardpb_proto_goTypes,
		DependencyIndexes: file_bulletinboardpb_proto_depIdxs,
		MessageInfos:      file_bulletinboardpb_proto_msgTypes,
	}.Build()
	File_bulletinboardpb_proto = out.File
	file_bulletinboardpb_proto_goTypes = nil
	file_bulletinboardpb_proto_depIdxs = nil
}
