// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: corepb.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The purchase ItemNotify currently carries an empty display payload. Keeping
// the message typed preserves the wire field and supports populated data later.
type ItemShow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellPrice     *Item                  `protobuf:"bytes,4,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"` // Currency and amount shown as the item's sale value.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShow) Reset() {
	*x = ItemShow{}
	mi := &file_corepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShow) ProtoMessage() {}

func (x *ItemShow) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShow.ProtoReflect.Descriptor instead.
func (*ItemShow) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{0}
}

func (x *ItemShow) GetSellPrice() *Item {
	if x != nil {
		return x.SellPrice
	}
	return nil
}

type Item struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count      int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ExpireTime int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	// Field 4 is reserved by the game protocol.
	// google.protobuf.Any detail = 5;
	Uid           int64     `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	IsNew         bool      `protobuf:"varint,7,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	MutantTypes   []int64   `protobuf:"varint,8,rep,packed,name=mutant_types,json=mutantTypes,proto3" json:"mutant_types,omitempty"`
	Show          *ItemShow `protobuf:"bytes,100,opt,name=show,proto3" json:"show,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_corepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Item) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Item) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Item) GetMutantTypes() []int64 {
	if x != nil {
		return x.MutantTypes
	}
	return nil
}

func (x *Item) GetShow() *ItemShow {
	if x != nil {
		return x.Show
	}
	return nil
}

type ItemBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	mi := &file_corepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{2}
}

func (x *ItemBag) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemChg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemChg) Reset() {
	*x = ItemChg{}
	mi := &file_corepb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemChg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChg) ProtoMessage() {}

func (x *ItemChg) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChg.ProtoReflect.Descriptor instead.
func (*ItemChg) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{3}
}

func (x *ItemChg) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemChg) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_corepb_proto protoreflect.FileDescriptor

const file_corepb_proto_rawDesc = "" +
	"\n" +
	"\fcorepb.proto\x12\x06corepb\"7\n" +
	"\bItemShow\x12+\n" +
	"\n" +
	"sell_price\x18\x04 \x01(\v2\f.corepb.ItemR\tsellPrice\"\xbf\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\x03R\x03uid\x12\x15\n" +
	"\x06is_new\x18\a \x01(\bR\x05isNew\x12!\n" +
	"\fmutant_types\x18\b \x03(\x03R\vmutantTypes\x12$\n" +
	"\x04show\x18d \x01(\v2\x10.corepb.ItemShowR\x04show\"-\n" +
	"\aItemBag\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"A\n" +
	"\aItemChg\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.corepb.ItemR\x04item\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05deltaBCZAgithub.com/MQEnergy/go-skeleton/internal/farm/proto/corepb;corepbb\x06proto3"

var (
	file_corepb_proto_rawDescOnce sync.Once
	file_corepb_proto_rawDescData []byte
)

func file_corepb_proto_rawDescGZIP() []byte {
	file_corepb_proto_rawDescOnce.Do(func() {
		file_corepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corepb_proto_rawDesc), len(file_corepb_proto_rawDesc)))
	})
	return file_corepb_proto_rawDescData
}

var file_corepb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_corepb_proto_goTypes = []any{
	(*ItemShow)(nil), // 0: corepb.ItemShow
	(*Item)(nil),     // 1: corepb.Item
	(*ItemBag)(nil),  // 2: corepb.ItemBag
	(*ItemChg)(nil),  // 3: corepb.ItemChg
}
var file_corepb_proto_depIdxs = []int32{
	1, // 0: corepb.ItemShow.sell_price:type_name -> corepb.Item
	0, // 1: corepb.Item.show:type_name -> corepb.ItemShow
	1, // 2: corepb.ItemBag.items:type_name -> corepb.Item
	1, // 3: corepb.ItemChg.item:type_name -> corepb.Item
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_corepb_proto_init() }
func file_corepb_proto_init() {
	if File_corepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corepb_proto_rawDesc), len(file_corepb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_corepb_proto_goTypes,
		DependencyIndexes: file_corepb_proto_depIdxs,
		MessageInfos:      file_corepb_proto_msgTypes,
	}.Build()
	File_corepb_proto = out.File
	file_corepb_proto_goTypes = nil
	file_corepb_proto_depIdxs = nil
}
