// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: friendpb.proto

package friendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 好友农场摘要信息 ============
type Plant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DryTimeSec    int64                  `protobuf:"varint,1,opt,name=dry_time_sec,json=dryTimeSec,proto3" json:"dry_time_sec,omitempty"`          // 缺水倒计时秒
	WeedTimeSec   int64                  `protobuf:"varint,2,opt,name=weed_time_sec,json=weedTimeSec,proto3" json:"weed_time_sec,omitempty"`       // 长草倒计时秒
	InsectTimeSec int64                  `protobuf:"varint,3,opt,name=insect_time_sec,json=insectTimeSec,proto3" json:"insect_time_sec,omitempty"` // 生虫倒计时秒
	RipeTimeSec   int64                  `protobuf:"varint,4,opt,name=ripe_time_sec,json=ripeTimeSec,proto3" json:"ripe_time_sec,omitempty"`       // 成熟倒计时秒
	RipeFruitId   int64                  `protobuf:"varint,5,opt,name=ripe_fruit_id,json=ripeFruitId,proto3" json:"ripe_fruit_id,omitempty"`       // 成熟果实ID
	StealPlantNum int64                  `protobuf:"varint,6,opt,name=steal_plant_num,json=stealPlantNum,proto3" json:"steal_plant_num,omitempty"` // 可偷数量
	DryNum        int64                  `protobuf:"varint,7,opt,name=dry_num,json=dryNum,proto3" json:"dry_num,omitempty"`                        // 缺水地块数
	WeedNum       int64                  `protobuf:"varint,8,opt,name=weed_num,json=weedNum,proto3" json:"weed_num,omitempty"`                     // 有草地块数
	InsectNum     int64                  `protobuf:"varint,9,opt,name=insect_num,json=insectNum,proto3" json:"insect_num,omitempty"`               // 有虫地块数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plant) Reset() {
	*x = Plant{}
	mi := &file_friendpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetDryTimeSec() int64 {
	if x != nil {
		return x.DryTimeSec
	}
	return 0
}

func (x *Plant) GetWeedTimeSec() int64 {
	if x != nil {
		return x.WeedTimeSec
	}
	return 0
}

func (x *Plant) GetInsectTimeSec() int64 {
	if x != nil {
		return x.InsectTimeSec
	}
	return 0
}

func (x *Plant) GetRipeTimeSec() int64 {
	if x != nil {
		return x.RipeTimeSec
	}
	return 0
}

func (x *Plant) GetRipeFruitId() int64 {
	if x != nil {
		return x.RipeFruitId
	}
	return 0
}

func (x *Plant) GetStealPlantNum() int64 {
	if x != nil {
		return x.StealPlantNum
	}
	return 0
}

func (x *Plant) GetDryNum() int64 {
	if x != nil {
		return x.DryNum
	}
	return 0
}

func (x *Plant) GetWeedNum() int64 {
	if x != nil {
		return x.WeedNum
	}
	return 0
}

func (x *Plant) GetInsectNum() int64 {
	if x != nil {
		return x.InsectNum
	}
	return 0
}

// ============ 标签 ============
type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNew         bool                   `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsFollow      bool                   `protobuf:"varint,2,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_friendpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{1}
}

func (x *Tags) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Tags) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

// ============ 好友信息 ============
type GameFriend struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gid              int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	OpenId           string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Remark           string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Level            int64                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Gold             int64                  `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`
	Tags             *Tags                  `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	Plant            *Plant                 `protobuf:"bytes,9,opt,name=plant,proto3" json:"plant,omitempty"`
	AuthorizedStatus int32                  `protobuf:"varint,10,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameFriend) Reset() {
	*x = GameFriend{}
	mi := &file_friendpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFriend) ProtoMessage() {}

func (x *GameFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFriend.ProtoReflect.Descriptor instead.
func (*GameFriend) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{2}
}

func (x *GameFriend) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GameFriend) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *GameFriend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameFriend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GameFriend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GameFriend) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameFriend) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GameFriend) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GameFriend) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

func (x *GameFriend) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

// --- 获取所有好友 ---
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_friendpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{3}
}

type GetAllReply struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	GameFriends []*GameFriend          `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	// repeated Invitation invitations = 2;  // 略
	ApplicationCount int64 `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	mi := &file_friendpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *GetAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

// --- 获取指定游戏好友 (通过GID列表) ---
type GetGameFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gids          []int64                `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameFriendsRequest) Reset() {
	*x = GetGameFriendsRequest{}
	mi := &file_friendpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameFriendsRequest) ProtoMessage() {}

func (x *GetGameFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetGameFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameFriendsRequest) GetGids() []int64 {
	if x != nil {
		return x.Gids
	}
	return nil
}

type GetGameFriendsReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameFriends      []*GameFriend          `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	ApplicationCount int64                  `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGameFriendsReply) Reset() {
	*x = GetGameFriendsReply{}
	mi := &file_friendpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameFriendsReply) ProtoMessage() {}

func (x *GetGameFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameFriendsReply.ProtoReflect.Descriptor instead.
func (*GetGameFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{6}
}

func (x *GetGameFriendsReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *GetGameFriendsReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

// --- 同步好友 (带 open_ids) ---
type SyncAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field 1 reserved
	OpenIds       []string `protobuf:"bytes,2,rep,name=open_ids,json=openIds,proto3" json:"open_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllRequest) Reset() {
	*x = SyncAllRequest{}
	mi := &file_friendpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllRequest) ProtoMessage() {}

func (x *SyncAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllRequest.ProtoReflect.Descriptor instead.
func (*SyncAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAllRequest) GetOpenIds() []string {
	if x != nil {
		return x.OpenIds
	}
	return nil
}

type SyncAllReply struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	GameFriends []*GameFriend          `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	// repeated Invitation invitations = 2;  // 略
	ApplicationCount int64 `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncAllReply) Reset() {
	*x = SyncAllReply{}
	mi := &file_friendpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllReply) ProtoMessage() {}

func (x *SyncAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllReply.ProtoReflect.Descriptor instead.
func (*SyncAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{8}
}

func (x *SyncAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *SyncAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

// 申请信息
type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	TimeAt        int64                  `protobuf:"varint,2,opt,name=time_at,json=timeAt,proto3" json:"time_at,omitempty"`
	OpenId        string                 `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Level         int64                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"` // repeated AvatarFrame equip_avatar_frames = 7;  // 略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_friendpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{9}
}

func (x *Application) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Application) GetTimeAt() int64 {
	if x != nil {
		return x.TimeAt
	}
	return 0
}

func (x *Application) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Application) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

// --- 获取好友申请列表 ---
type GetApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsRequest) Reset() {
	*x = GetApplicationsRequest{}
	mi := &file_friendpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsRequest) ProtoMessage() {}

func (x *GetApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{10}
}

type GetApplicationsReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Applications      []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	BlockApplications bool                   `protobuf:"varint,2,opt,name=block_applications,json=blockApplications,proto3" json:"block_applications,omitempty"` // 是否屏蔽申请
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetApplicationsReply) Reset() {
	*x = GetApplicationsReply{}
	mi := &file_friendpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsReply) ProtoMessage() {}

func (x *GetApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsReply.ProtoReflect.Descriptor instead.
func (*GetApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{11}
}

func (x *GetApplicationsReply) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *GetApplicationsReply) GetBlockApplications() bool {
	if x != nil {
		return x.BlockApplications
	}
	return false
}

// --- 同意好友申请 ---
type AcceptFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGids    []int64                `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendsRequest) Reset() {
	*x = AcceptFriendsRequest{}
	mi := &file_friendpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsRequest) ProtoMessage() {}

func (x *AcceptFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type AcceptFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*GameFriend          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendsReply) Reset() {
	*x = AcceptFriendsReply{}
	mi := &file_friendpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsReply) ProtoMessage() {}

func (x *AcceptFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsReply.ProtoReflect.Descriptor instead.
func (*AcceptFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptFriendsReply) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

// --- 拒绝好友申请 ---
type RejectFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGids    []int64                `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendsRequest) Reset() {
	*x = RejectFriendsRequest{}
	mi := &file_friendpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsRequest) ProtoMessage() {}

func (x *RejectFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{14}
}

func (x *RejectFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type RejectFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendsReply) Reset() {
	*x = RejectFriendsReply{}
	mi := &file_friendpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsReply) ProtoMessage() {}

func (x *RejectFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsReply.ProtoReflect.Descriptor instead.
func (*RejectFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{15}
}

// --- 设置屏蔽申请 ---
type SetBlockApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         bool                   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockApplicationsRequest) Reset() {
	*x = SetBlockApplicationsRequest{}
	mi := &file_friendpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsRequest) ProtoMessage() {}

func (x *SetBlockApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsRequest.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{16}
}

func (x *SetBlockApplicationsRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type SetBlockApplicationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         bool                   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockApplicationsReply) Reset() {
	*x = SetBlockApplicationsReply{}
	mi := &file_friendpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsReply) ProtoMessage() {}

func (x *SetBlockApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsReply.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{17}
}

func (x *SetBlockApplicationsReply) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

// --- 获取分享Key ---
type GetShareKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareCfgId    int64                  `protobuf:"varint,1,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareKeyRequest) Reset() {
	*x = GetShareKeyRequest{}
	mi := &file_friendpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareKeyRequest) ProtoMessage() {}

func (x *GetShareKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareKeyRequest.ProtoReflect.Descriptor instead.
func (*GetShareKeyRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{18}
}

func (x *GetShareKeyRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

type GetShareKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareKey      string                 `protobuf:"bytes,1,opt,name=share_key,json=shareKey,proto3" json:"share_key,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,2,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	ShareCfgId    int64                  `protobuf:"varint,3,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareKeyReply) Reset() {
	*x = GetShareKeyReply{}
	mi := &file_friendpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareKeyReply) ProtoMessage() {}

func (x *GetShareKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareKeyReply.ProtoReflect.Descriptor instead.
func (*GetShareKeyReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{19}
}

func (x *GetShareKeyReply) GetShareKey() string {
	if x != nil {
		return x.ShareKey
	}
	return ""
}

func (x *GetShareKeyReply) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *GetShareKeyReply) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

// 收到好友申请通知
type FriendApplicationReceivedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplicationReceivedNotify) Reset() {
	*x = FriendApplicationReceivedNotify{}
	mi := &file_friendpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplicationReceivedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplicationReceivedNotify) ProtoMessage() {}

func (x *FriendApplicationReceivedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplicationReceivedNotify.ProtoReflect.Descriptor instead.
func (*FriendApplicationReceivedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{20}
}

func (x *FriendApplicationReceivedNotify) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// 好友添加成功通知 (对方同意后)
type FriendAddedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*GameFriend          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddedNotify) Reset() {
	*x = FriendAddedNotify{}
	mi := &file_friendpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddedNotify) ProtoMessage() {}

func (x *FriendAddedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddedNotify.ProtoReflect.Descriptor instead.
func (*FriendAddedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{21}
}

func (x *FriendAddedNotify) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_friendpb_proto protoreflect.FileDescriptor

const file_friendpb_proto_rawDesc = "" +
	"\n" +
	"\x0efriendpb.proto\x12\x0fgamepb.friendpb\"\xb8\x02\n" +
	"\x05Plant\x12 \n" +
	"\fdry_time_sec\x18\x01 \x01(\x03R\n" +
	"dryTimeSec\x12\"\n" +
	"\rweed_time_sec\x18\x02 \x01(\x03R\vweedTimeSec\x12&\n" +
	"\x0finsect_time_sec\x18\x03 \x01(\x03R\rinsectTimeSec\x12\"\n" +
	"\rripe_time_sec\x18\x04 \x01(\x03R\vripeTimeSec\x12\"\n" +
	"\rripe_fruit_id\x18\x05 \x01(\x03R\vripeFruitId\x12&\n" +
	"\x0fsteal_plant_num\x18\x06 \x01(\x03R\rstealPlantNum\x12\x17\n" +
	"\adry_num\x18\a \x01(\x03R\x06dryNum\x12\x19\n" +
	"\bweed_num\x18\b \x01(\x03R\aweedNum\x12\x1d\n" +
	"\n" +
	"insect_num\x18\t \x01(\x03R\tinsectNum\":\n" +
	"\x04Tags\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew\x12\x1b\n" +
	"\tis_follow\x18\x02 \x01(\bR\bisFollow\"\xb2\x02\n" +
	"\n" +
	"GameFriend\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x03R\x05level\x12\x12\n" +
	"\x04gold\x18\a \x01(\x03R\x04gold\x12)\n" +
	"\x04tags\x18\b \x01(\v2\x15.gamepb.friendpb.TagsR\x04tags\x12,\n" +
	"\x05plant\x18\t \x01(\v2\x16.gamepb.friendpb.PlantR\x05plant\x12+\n" +
	"\x11authorized_status\x18\n" +
	" \x01(\x05R\x10authorizedStatus\"\x0f\n" +
	"\rGetAllRequest\"z\n" +
	"\vGetAllReply\x12>\n" +
	"\fgame_friends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\vgameFriends\x12+\n" +
	"\x11application_count\x18\x03 \x01(\x03R\x10applicationCount\"+\n" +
	"\x15GetGameFriendsRequest\x12\x12\n" +
	"\x04gids\x18\x01 \x03(\x03R\x04gids\"\x82\x01\n" +
	"\x13GetGameFriendsReply\x12>\n" +
	"\fgame_friends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\vgameFriends\x12+\n" +
	"\x11application_count\x18\x03 \x01(\x03R\x10applicationCount\"+\n" +
	"\x0eSyncAllRequest\x12\x19\n" +
	"\bopen_ids\x18\x02 \x03(\tR\aopenIds\"{\n" +
	"\fSyncAllReply\x12>\n" +
	"\fgame_friends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\vgameFriends\x12+\n" +
	"\x11application_count\x18\x03 \x01(\x03R\x10applicationCount\"\x9a\x01\n" +
	"\vApplication\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x17\n" +
	"\atime_at\x18\x02 \x01(\x03R\x06timeAt\x12\x17\n" +
	"\aopen_id\x18\x03 \x01(\tR\x06openId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x03R\x05level\"\x18\n" +
	"\x16GetApplicationsRequest\"\x87\x01\n" +
	"\x14GetApplicationsReply\x12@\n" +
	"\fapplications\x18\x01 \x03(\v2\x1c.gamepb.friendpb.ApplicationR\fapplications\x12-\n" +
	"\x12block_applications\x18\x02 \x01(\bR\x11blockApplications\"7\n" +
	"\x14AcceptFriendsRequest\x12\x1f\n" +
	"\vfriend_gids\x18\x01 \x03(\x03R\n" +
	"friendGids\"K\n" +
	"\x12AcceptFriendsReply\x125\n" +
	"\afriends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\afriends\"7\n" +
	"\x14RejectFriendsRequest\x12\x1f\n" +
	"\vfriend_gids\x18\x01 \x03(\x03R\n" +
	"friendGids\"\x14\n" +
	"\x12RejectFriendsReply\"3\n" +
	"\x1bSetBlockApplicationsRequest\x12\x14\n" +
	"\x05block\x18\x01 \x01(\bR\x05block\"1\n" +
	"\x19SetBlockApplicationsReply\x12\x14\n" +
	"\x05block\x18\x01 \x01(\bR\x05block\"6\n" +
	"\x12GetShareKeyRequest\x12 \n" +
	"\fshare_cfg_id\x18\x01 \x01(\x03R\n" +
	"shareCfgId\"n\n" +
	"\x10GetShareKeyReply\x12\x1b\n" +
	"\tshare_key\x18\x01 \x01(\tR\bshareKey\x12\x1b\n" +
	"\tshare_url\x18\x02 \x01(\tR\bshareUrl\x12 \n" +
	"\fshare_cfg_id\x18\x03 \x01(\x03R\n" +
	"shareCfgId\"c\n" +
	"\x1fFriendApplicationReceivedNotify\x12@\n" +
	"\fapplications\x18\x01 \x03(\v2\x1c.gamepb.friendpb.ApplicationR\fapplications\"J\n" +
	"\x11FriendAddedNotify\x125\n" +
	"\afriends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\afriendsBJZHgithub.com/it00021hot/qq-farm-core/internal/farm/proto/friendpb;friendpbb\x06proto3"

var (
	file_friendpb_proto_rawDescOnce sync.Once
	file_friendpb_proto_rawDescData []byte
)

func file_friendpb_proto_rawDescGZIP() []byte {
	file_friendpb_proto_rawDescOnce.Do(func() {
		file_friendpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friendpb_proto_rawDesc), len(file_friendpb_proto_rawDesc)))
	})
	return file_friendpb_proto_rawDescData
}

var file_friendpb_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_friendpb_proto_goTypes = []any{
	(*Plant)(nil),                           // 0: gamepb.friendpb.Plant
	(*Tags)(nil),                            // 1: gamepb.friendpb.Tags
	(*GameFriend)(nil),                      // 2: gamepb.friendpb.GameFriend
	(*GetAllRequest)(nil),                   // 3: gamepb.friendpb.GetAllRequest
	(*GetAllReply)(nil),                     // 4: gamepb.friendpb.GetAllReply
	(*GetGameFriendsRequest)(nil),           // 5: gamepb.friendpb.GetGameFriendsRequest
	(*GetGameFriendsReply)(nil),             // 6: gamepb.friendpb.GetGameFriendsReply
	(*SyncAllRequest)(nil),                  // 7: gamepb.friendpb.SyncAllRequest
	(*SyncAllReply)(nil),                    // 8: gamepb.friendpb.SyncAllReply
	(*Application)(nil),                     // 9: gamepb.friendpb.Application
	(*GetApplicationsRequest)(nil),          // 10: gamepb.friendpb.GetApplicationsRequest
	(*GetApplicationsReply)(nil),            // 11: gamepb.friendpb.GetApplicationsReply
	(*AcceptFriendsRequest)(nil),            // 12: gamepb.friendpb.AcceptFriendsRequest
	(*AcceptFriendsReply)(nil),              // 13: gamepb.friendpb.AcceptFriendsReply
	(*RejectFriendsRequest)(nil),            // 14: gamepb.friendpb.RejectFriendsRequest
	(*RejectFriendsReply)(nil),              // 15: gamepb.friendpb.RejectFriendsReply
	(*SetBlockApplicationsRequest)(nil),     // 16: gamepb.friendpb.SetBlockApplicationsRequest
	(*SetBlockApplicationsReply)(nil),       // 17: gamepb.friendpb.SetBlockApplicationsReply
	(*GetShareKeyRequest)(nil),              // 18: gamepb.friendpb.GetShareKeyRequest
	(*GetShareKeyReply)(nil),                // 19: gamepb.friendpb.GetShareKeyReply
	(*FriendApplicationReceivedNotify)(nil), // 20: gamepb.friendpb.FriendApplicationReceivedNotify
	(*FriendAddedNotify)(nil),               // 21: gamepb.friendpb.FriendAddedNotify
}
var file_friendpb_proto_depIdxs = []int32{
	1, // 0: gamepb.friendpb.GameFriend.tags:type_name -> gamepb.friendpb.Tags
	0, // 1: gamepb.friendpb.GameFriend.plant:type_name -> gamepb.friendpb.Plant
	2, // 2: gamepb.friendpb.GetAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	2, // 3: gamepb.friendpb.GetGameFriendsReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	2, // 4: gamepb.friendpb.SyncAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	9, // 5: gamepb.friendpb.GetApplicationsReply.applications:type_name -> gamepb.friendpb.Application
	2, // 6: gamepb.friendpb.AcceptFriendsReply.friends:type_name -> gamepb.friendpb.GameFriend
	9, // 7: gamepb.friendpb.FriendApplicationReceivedNotify.applications:type_name -> gamepb.friendpb.Application
	2, // 8: gamepb.friendpb.FriendAddedNotify.friends:type_name -> gamepb.friendpb.GameFriend
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_friendpb_proto_init() }
func file_friendpb_proto_init() {
	if File_friendpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friendpb_proto_rawDesc), len(file_friendpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friendpb_proto_goTypes,
		DependencyIndexes: file_friendpb_proto_depIdxs,
		MessageInfos:      file_friendpb_proto_msgTypes,
	}.Build()
	File_friendpb_proto = out.File
	file_friendpb_proto_goTypes = nil
	file_friendpb_proto_depIdxs = nil
}
