// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: itempb.proto

package itempb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取背包
type BagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagRequest) Reset() {
	*x = BagRequest{}
	mi := &file_itempb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagRequest) ProtoMessage() {}

func (x *BagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagRequest.ProtoReflect.Descriptor instead.
func (*BagRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{0}
}

type BagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemBag       *corepb.ItemBag        `protobuf:"bytes,1,opt,name=item_bag,json=itemBag,proto3" json:"item_bag,omitempty"` // 与 game 一致，背包数据在 item_bag 里
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagReply) Reset() {
	*x = BagReply{}
	mi := &file_itempb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagReply) ProtoMessage() {}

func (x *BagReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagReply.ProtoReflect.Descriptor instead.
func (*BagReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{1}
}

func (x *BagReply) GetItemBag() *corepb.ItemBag {
	if x != nil {
		return x.ItemBag
	}
	return nil
}

type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 要出售的物品列表 (id + count)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_itempb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{2}
}

func (x *SellRequest) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SellReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellItems     []*corepb.Item         `protobuf:"bytes,1,rep,name=sell_items,json=sellItems,proto3" json:"sell_items,omitempty"` // 出售的物品
	GetItems      []*corepb.Item         `protobuf:"bytes,2,rep,name=get_items,json=getItems,proto3" json:"get_items,omitempty"`    // 获得的物品（常见: 1001=金币, 1002=点券）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellReply) Reset() {
	*x = SellReply{}
	mi := &file_itempb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellReply) ProtoMessage() {}

func (x *SellReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellReply.ProtoReflect.Descriptor instead.
func (*SellReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{3}
}

func (x *SellReply) GetSellItems() []*corepb.Item {
	if x != nil {
		return x.SellItems
	}
	return nil
}

func (x *SellReply) GetGetItems() []*corepb.Item {
	if x != nil {
		return x.GetItems
	}
	return nil
}

type UseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LandIds       []int64                `protobuf:"varint,3,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseRequest) Reset() {
	*x = UseRequest{}
	mi := &file_itempb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseRequest) ProtoMessage() {}

func (x *UseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseRequest.ProtoReflect.Descriptor instead.
func (*UseRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{4}
}

func (x *UseRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UseRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

type UseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseReply) Reset() {
	*x = UseReply{}
	mi := &file_itempb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseReply) ProtoMessage() {}

func (x *UseReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseReply.ProtoReflect.Descriptor instead.
func (*UseReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{5}
}

func (x *UseReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUseRequest) Reset() {
	*x = BatchUseRequest{}
	mi := &file_itempb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUseRequest) ProtoMessage() {}

func (x *BatchUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUseRequest.ProtoReflect.Descriptor instead.
func (*BatchUseRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchUseRequest) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchUseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedItems     []*corepb.Item         `protobuf:"bytes,1,rep,name=used_items,json=usedItems,proto3" json:"used_items,omitempty"`
	Items         []*corepb.Item         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUseReply) Reset() {
	*x = BatchUseReply{}
	mi := &file_itempb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUseReply) ProtoMessage() {}

func (x *BatchUseReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUseReply.ProtoReflect.Descriptor instead.
func (*BatchUseReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchUseReply) GetUsedItems() []*corepb.Item {
	if x != nil {
		return x.UsedItems
	}
	return nil
}

func (x *BatchUseReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CannelNewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CannelNewRequest) Reset() {
	*x = CannelNewRequest{}
	mi := &file_itempb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CannelNewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CannelNewRequest) ProtoMessage() {}

func (x *CannelNewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CannelNewRequest.ProtoReflect.Descriptor instead.
func (*CannelNewRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{8}
}

func (x *CannelNewRequest) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CannelNewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CannelNewReply) Reset() {
	*x = CannelNewReply{}
	mi := &file_itempb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CannelNewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CannelNewReply) ProtoMessage() {}

func (x *CannelNewReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CannelNewReply.ProtoReflect.Descriptor instead.
func (*CannelNewReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{9}
}

var File_itempb_proto protoreflect.FileDescriptor

const file_itempb_proto_rawDesc = "" +
	"\n" +
	"\fitempb.proto\x12\rgamepb.itempb\x1a\fcorepb.proto\"\f\n" +
	"\n" +
	"BagRequest\"6\n" +
	"\bBagReply\x12*\n" +
	"\bitem_bag\x18\x01 \x01(\v2\x0f.corepb.ItemBagR\aitemBag\"1\n" +
	"\vSellRequest\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"c\n" +
	"\tSellReply\x12+\n" +
	"\n" +
	"sell_items\x18\x01 \x03(\v2\f.corepb.ItemR\tsellItems\x12)\n" +
	"\tget_items\x18\x02 \x03(\v2\f.corepb.ItemR\bgetItems\"V\n" +
	"\n" +
	"UseRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x19\n" +
	"\bland_ids\x18\x03 \x03(\x03R\alandIds\".\n" +
	"\bUseReply\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"5\n" +
	"\x0fBatchUseRequest\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"`\n" +
	"\rBatchUseReply\x12+\n" +
	"\n" +
	"used_items\x18\x01 \x03(\v2\f.corepb.ItemR\tusedItems\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.corepb.ItemR\x05items\"6\n" +
	"\x10CannelNewRequest\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.corepb.ItemR\x05items\"\x10\n" +
	"\x0eCannelNewReplyBFZDgithub.com/it00021hot/qq-farm-core/internal/farm/proto/itempb;itempbb\x06proto3"

var (
	file_itempb_proto_rawDescOnce sync.Once
	file_itempb_proto_rawDescData []byte
)

func file_itempb_proto_rawDescGZIP() []byte {
	file_itempb_proto_rawDescOnce.Do(func() {
		file_itempb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_itempb_proto_rawDesc), len(file_itempb_proto_rawDesc)))
	})
	return file_itempb_proto_rawDescData
}

var file_itempb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_itempb_proto_goTypes = []any{
	(*BagRequest)(nil),       // 0: gamepb.itempb.BagRequest
	(*BagReply)(nil),         // 1: gamepb.itempb.BagReply
	(*SellRequest)(nil),      // 2: gamepb.itempb.SellRequest
	(*SellReply)(nil),        // 3: gamepb.itempb.SellReply
	(*UseRequest)(nil),       // 4: gamepb.itempb.UseRequest
	(*UseReply)(nil),         // 5: gamepb.itempb.UseReply
	(*BatchUseRequest)(nil),  // 6: gamepb.itempb.BatchUseRequest
	(*BatchUseReply)(nil),    // 7: gamepb.itempb.BatchUseReply
	(*CannelNewRequest)(nil), // 8: gamepb.itempb.CannelNewRequest
	(*CannelNewReply)(nil),   // 9: gamepb.itempb.CannelNewReply
	(*corepb.ItemBag)(nil),   // 10: corepb.ItemBag
	(*corepb.Item)(nil),      // 11: corepb.Item
}
var file_itempb_proto_depIdxs = []int32{
	10, // 0: gamepb.itempb.BagReply.item_bag:type_name -> corepb.ItemBag
	11, // 1: gamepb.itempb.SellRequest.items:type_name -> corepb.Item
	11, // 2: gamepb.itempb.SellReply.sell_items:type_name -> corepb.Item
	11, // 3: gamepb.itempb.SellReply.get_items:type_name -> corepb.Item
	11, // 4: gamepb.itempb.UseReply.items:type_name -> corepb.Item
	11, // 5: gamepb.itempb.BatchUseRequest.items:type_name -> corepb.Item
	11, // 6: gamepb.itempb.BatchUseReply.used_items:type_name -> corepb.Item
	11, // 7: gamepb.itempb.BatchUseReply.items:type_name -> corepb.Item
	11, // 8: gamepb.itempb.CannelNewRequest.items:type_name -> corepb.Item
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_itempb_proto_init() }
func file_itempb_proto_init() {
	if File_itempb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_itempb_proto_rawDesc), len(file_itempb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itempb_proto_goTypes,
		DependencyIndexes: file_itempb_proto_depIdxs,
		MessageInfos:      file_itempb_proto_msgTypes,
	}.Build()
	File_itempb_proto = out.File
	file_itempb_proto_goTypes = nil
	file_itempb_proto_depIdxs = nil
}
