// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: notifypb.proto

package itempb

import (
	corepb "github.com/it00021hot/qq-farm-core/internal/farm/proto/corepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 物品变化通知 ============
type ItemNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*corepb.ItemChg      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemNotify) Reset() {
	*x = ItemNotify{}
	mi := &file_notifypb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNotify) ProtoMessage() {}

func (x *ItemNotify) ProtoReflect() protoreflect.Message {
	mi := &file_notifypb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNotify.ProtoReflect.Descriptor instead.
func (*ItemNotify) Descriptor() ([]byte, []int) {
	return file_notifypb_proto_rawDescGZIP(), []int{0}
}

func (x *ItemNotify) GetItems() []*corepb.ItemChg {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_notifypb_proto protoreflect.FileDescriptor

const file_notifypb_proto_rawDesc = "" +
	"\n" +
	"\x0enotifypb.proto\x12\rgamepb.itempb\x1a\fcorepb.proto\"3\n" +
	"\n" +
	"ItemNotify\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.corepb.ItemChgR\x05itemsBFZDgithub.com/it00021hot/qq-farm-core/internal/farm/proto/itempb;itempbb\x06proto3"

var (
	file_notifypb_proto_rawDescOnce sync.Once
	file_notifypb_proto_rawDescData []byte
)

func file_notifypb_proto_rawDescGZIP() []byte {
	file_notifypb_proto_rawDescOnce.Do(func() {
		file_notifypb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifypb_proto_rawDesc), len(file_notifypb_proto_rawDesc)))
	})
	return file_notifypb_proto_rawDescData
}

var file_notifypb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notifypb_proto_goTypes = []any{
	(*ItemNotify)(nil),     // 0: gamepb.itempb.ItemNotify
	(*corepb.ItemChg)(nil), // 1: corepb.ItemChg
}
var file_notifypb_proto_depIdxs = []int32{
	1, // 0: gamepb.itempb.ItemNotify.items:type_name -> corepb.ItemChg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notifypb_proto_init() }
func file_notifypb_proto_init() {
	if File_notifypb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifypb_proto_rawDesc), len(file_notifypb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notifypb_proto_goTypes,
		DependencyIndexes: file_notifypb_proto_depIdxs,
		MessageInfos:      file_notifypb_proto_msgTypes,
	}.Build()
	File_notifypb_proto = out.File
	file_notifypb_proto_goTypes = nil
	file_notifypb_proto_depIdxs = nil
}
