// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: weatherpb.proto

package weatherpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 当前农场的特殊天气。雨落成诗活动中 weather_type=1 表示雷雨。
type WeatherStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WeatherType int64                  `protobuf:"varint,1,opt,name=weather_type,json=weatherType,proto3" json:"weather_type,omitempty"`
	Status      int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	BeginTime   int64                  `protobuf:"varint,3,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime     int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Source      int64                  `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	Field_8     int64                  `protobuf:"varint,8,opt,name=field_8,json=field8,proto3" json:"field_8,omitempty"`
	// 好友现场天气附带的活动标记。实机已见晴天=1、雷雨已采=4；
	// 不能再沿用旧实现把 field_8 当作该标记。
	Field_9       int64 `protobuf:"varint,9,opt,name=field_9,json=field9,proto3" json:"field_9,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherStatus) Reset() {
	*x = WeatherStatus{}
	mi := &file_weatherpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherStatus) ProtoMessage() {}

func (x *WeatherStatus) ProtoReflect() protoreflect.Message {
	mi := &file_weatherpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherStatus.ProtoReflect.Descriptor instead.
func (*WeatherStatus) Descriptor() ([]byte, []int) {
	return file_weatherpb_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherStatus) GetWeatherType() int64 {
	if x != nil {
		return x.WeatherType
	}
	return 0
}

func (x *WeatherStatus) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WeatherStatus) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *WeatherStatus) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *WeatherStatus) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *WeatherStatus) GetField_8() int64 {
	if x != nil {
		return x.Field_8
	}
	return 0
}

func (x *WeatherStatus) GetField_9() int64 {
	if x != nil {
		return x.Field_9
	}
	return 0
}

type GetWeatherStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherStatusRequest) Reset() {
	*x = GetWeatherStatusRequest{}
	mi := &file_weatherpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherStatusRequest) ProtoMessage() {}

func (x *GetWeatherStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weatherpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherStatusRequest) Descriptor() ([]byte, []int) {
	return file_weatherpb_proto_rawDescGZIP(), []int{1}
}

type GetWeatherStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weather       *WeatherStatus         `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherStatusReply) Reset() {
	*x = GetWeatherStatusReply{}
	mi := &file_weatherpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherStatusReply) ProtoMessage() {}

func (x *GetWeatherStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_weatherpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherStatusReply.ProtoReflect.Descriptor instead.
func (*GetWeatherStatusReply) Descriptor() ([]byte, []int) {
	return file_weatherpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeatherStatusReply) GetWeather() *WeatherStatus {
	if x != nil {
		return x.Weather
	}
	return nil
}

type WeatherChangeNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weather       *WeatherStatus         `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherChangeNotify) Reset() {
	*x = WeatherChangeNotify{}
	mi := &file_weatherpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherChangeNotify) ProtoMessage() {}

func (x *WeatherChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_weatherpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherChangeNotify.ProtoReflect.Descriptor instead.
func (*WeatherChangeNotify) Descriptor() ([]byte, []int) {
	return file_weatherpb_proto_rawDescGZIP(), []int{3}
}

func (x *WeatherChangeNotify) GetWeather() *WeatherStatus {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *WeatherChangeNotify) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

var File_weatherpb_proto protoreflect.FileDescriptor

const file_weatherpb_proto_rawDesc = "" +
	"\n" +
	"\x0fweatherpb.proto\x12\x10gamepb.weatherpb\"\xce\x01\n" +
	"\rWeatherStatus\x12!\n" +
	"\fweather_type\x18\x01 \x01(\x03R\vweatherType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x03 \x01(\x03R\tbeginTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06source\x18\x05 \x01(\x03R\x06source\x12\x17\n" +
	"\afield_8\x18\b \x01(\x03R\x06field8\x12\x17\n" +
	"\afield_9\x18\t \x01(\x03R\x06field9\"\x19\n" +
	"\x17GetWeatherStatusRequest\"R\n" +
	"\x15GetWeatherStatusReply\x129\n" +
	"\aweather\x18\x01 \x01(\v2\x1f.gamepb.weatherpb.WeatherStatusR\aweather\"k\n" +
	"\x13WeatherChangeNotify\x129\n" +
	"\aweather\x18\x01 \x01(\v2\x1f.gamepb.weatherpb.WeatherStatusR\aweather\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGidb\x06proto3"

var (
	file_weatherpb_proto_rawDescOnce sync.Once
	file_weatherpb_proto_rawDescData []byte
)

func file_weatherpb_proto_rawDescGZIP() []byte {
	file_weatherpb_proto_rawDescOnce.Do(func() {
		file_weatherpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weatherpb_proto_rawDesc), len(file_weatherpb_proto_rawDesc)))
	})
	return file_weatherpb_proto_rawDescData
}

var file_weatherpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weatherpb_proto_goTypes = []any{
	(*WeatherStatus)(nil),           // 0: gamepb.weatherpb.WeatherStatus
	(*GetWeatherStatusRequest)(nil), // 1: gamepb.weatherpb.GetWeatherStatusRequest
	(*GetWeatherStatusReply)(nil),   // 2: gamepb.weatherpb.GetWeatherStatusReply
	(*WeatherChangeNotify)(nil),     // 3: gamepb.weatherpb.WeatherChangeNotify
}
var file_weatherpb_proto_depIdxs = []int32{
	0, // 0: gamepb.weatherpb.GetWeatherStatusReply.weather:type_name -> gamepb.weatherpb.WeatherStatus
	0, // 1: gamepb.weatherpb.WeatherChangeNotify.weather:type_name -> gamepb.weatherpb.WeatherStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weatherpb_proto_init() }
func file_weatherpb_proto_init() {
	if File_weatherpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weatherpb_proto_rawDesc), len(file_weatherpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weatherpb_proto_goTypes,
		DependencyIndexes: file_weatherpb_proto_depIdxs,
		MessageInfos:      file_weatherpb_proto_msgTypes,
	}.Build()
	File_weatherpb_proto = out.File
	file_weatherpb_proto_goTypes = nil
	file_weatherpb_proto_depIdxs = nil
}
