// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthRolePermission = "cn_auth_role_permission"

// AuthRolePermission mapped from table <cn_auth_role_permission>
type AuthRolePermission struct {
	ID        int    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	RoleID    int    `gorm:"column:role_id;type:int;not null;comment:角色ID" json:"role_id"`                   // 角色ID
	SourceIds string `gorm:"column:source_ids;type:text;not null;comment:资源id列表 1,2,3..." json:"source_ids"` // 资源id列表 1,2,3...
}

// TableName AuthRolePermission's table name
func (*AuthRolePermission) TableName() string {
	return TableNameAuthRolePermission
}
