// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysResource = "cn_sys_resource"

// SysResource 后台配置资源菜单表
type SysResource struct {
	ID             uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;type:varchar(64);not null;comment:名称" json:"name"`                                                   // 名称
	Alias_         string `gorm:"column:alias;type:varchar(64);not null;comment:别名" json:"alias"`                                                 // 别名
	Desc           string `gorm:"column:desc;type:varchar(64);not null;comment:描述" json:"desc"`                                                   // 描述
	FURL           string `gorm:"column:f_url;type:varchar(64);not null;comment:前端路由" json:"f_url"`                                               // 前端路由
	BURL           string `gorm:"column:b_url;type:varchar(64);not null;comment:后端接口" json:"b_url"`                                               // 后端接口
	Redirect       string `gorm:"column:redirect;type:varchar(128);not null;comment:重定向地址" json:"redirect"`                                       // 重定向地址
	CompPath       string `gorm:"column:comp_path;type:varchar(128);not null;comment:组件路径" json:"comp_path"`                                      // 组件路径
	Icon           string `gorm:"column:icon;type:varchar(32);not null;comment:菜单icon" json:"icon"`                                               // 菜单icon
	CIcon          string `gorm:"column:c_icon;type:varchar(32);not null;comment:自定义icon(优先)" json:"c_icon"`                                      // 自定义icon(优先)
	ParentID       uint64 `gorm:"column:parent_id;type:bigint unsigned;not null;comment:父级ID" json:"parent_id"`                                   // 父级ID
	Path           string `gorm:"column:path;type:varchar(64);not null;comment:ID路径 1-2-3..." json:"path"`                                        // ID路径 1-2-3...
	ResourceType   uint8  `gorm:"column:resource_type;type:tinyint unsigned;not null;default:1;comment:类型 1：目录 2：菜单 3：操作" json:"resource_type"`   // 类型 1：目录 2：菜单 3：操作
	IsHidden       uint8  `gorm:"column:is_hidden;type:tinyint unsigned;not null;comment:是否隐藏 1:是 0：不是" json:"is_hidden"`                         // 是否隐藏 1:是 0：不是
	IsCache        uint8  `gorm:"column:is_cache;type:tinyint unsigned;not null;comment:是否缓存 1:是 0：不是" json:"is_cache"`                           // 是否缓存 1:是 0：不是
	IsExternal     uint8  `gorm:"column:is_external;type:tinyint unsigned;not null;comment:是否外链 1:是 0:不是" json:"is_external"`                     // 是否外链 1:是 0:不是
	AlwaysShow     uint8  `gorm:"column:always_show;type:tinyint unsigned;not null;comment:总是显示 1:是 0:不是" json:"always_show"`                     // 总是显示 1:是 0:不是
	BreadcrumbShow uint8  `gorm:"column:breadcrumb_show;type:tinyint unsigned;not null;comment:面包屑显示 1:是 0:不是" json:"breadcrumb_show"`            // 面包屑显示 1:是 0:不是
	IsAffix        uint8  `gorm:"column:is_affix;type:tinyint unsigned;not null;comment:是否固定在tab栏 1：是 0：不是" json:"is_affix"`                      // 是否固定在tab栏 1：是 0：不是
	ResType        uint8  `gorm:"column:res_type;type:tinyint unsigned;not null;default:1;comment:资源类型：1：平台型 2：商家型 3：代理商型 4：通用型" json:"res_type"` // 资源类型：1：平台型 2：商家型 3：代理商型 4：通用型
	Status         uint8  `gorm:"column:status;type:tinyint unsigned;not null;comment:状态：1：正常 2：停用" json:"status"`                                // 状态：1：正常 2：停用
	SortOrder      uint16 `gorm:"column:sort_order;type:smallint unsigned;not null;default:50;comment:排序" json:"sort_order"`                      // 排序
	CreatedAt      uint64 `gorm:"column:created_at;type:bigint unsigned;not null" json:"created_at"`
	UpdatedAt      uint64 `gorm:"column:updated_at;type:bigint unsigned;not null" json:"updated_at"`
}

// TableName SysResource's table name
func (*SysResource) TableName() string {
	return TableNameSysResource
}
