// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleAuth = "cn_sys_role_auth"

// SysRoleAuth 角色权限表
type SysRoleAuth struct {
	ID          uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RoleID      uint64 `gorm:"column:role_id;type:bigint unsigned;not null;comment:角色ID" json:"role_id"`           // 角色ID
	ResourceIds string `gorm:"column:resource_ids;type:text;not null;comment:菜单id列表 1,2,3..." json:"resource_ids"` // 菜单id列表 1,2,3...
}

// TableName SysRoleAuth's table name
func (*SysRoleAuth) TableName() string {
	return TableNameSysRoleAuth
}
